"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from api.power_service.v26 import power_service_pb2 as _power_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PowerServiceStub:
    """PowerService manages power operations"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PowerServiceAsyncStub: ...
    Reboot: _grpc.UnaryUnaryMultiCallable[_power_service_pb2.RebootRequest, _types_pb2.BooleanResponse]
    """Reboot reboots the system"""
    Shutdown: _grpc.UnaryUnaryMultiCallable[_power_service_pb2.ShutdownRequest, _types_pb2.BooleanResponse]
    """Shutdown shuts down the system"""

@_typing.type_check_only
class PowerServiceAsyncStub(PowerServiceStub):
    """PowerService manages power operations"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Reboot: _aio.UnaryUnaryMultiCallable[_power_service_pb2.RebootRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Reboot reboots the system"""
    Shutdown: _aio.UnaryUnaryMultiCallable[_power_service_pb2.ShutdownRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Shutdown shuts down the system"""

class PowerServiceServicer(metaclass=_abc_1.ABCMeta):
    """PowerService manages power operations"""

    @_abc_1.abstractmethod
    def Reboot(
        self,
        request: _power_service_pb2.RebootRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Reboot reboots the system"""

    @_abc_1.abstractmethod
    def Shutdown(
        self,
        request: _power_service_pb2.ShutdownRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Shutdown shuts down the system"""

def add_PowerServiceServicer_to_server(servicer: PowerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
