# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/power_service/v26/power_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/power_service/v26/power_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import types_pb2 as api_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)api/power_service/v26/power_service.proto\x12\x0f\x61pi.gravity.v26\x1a\x16\x61pi/common/types.proto\".\n\rRebootRequest\x12\r\n\x05\x66orce\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"0\n\x0fShutdownRequest\x12\r\n\x05\x66orce\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t*\x8d\x01\n\tPowerMode\x12\x1a\n\x16POWER_MODE_UNSPECIFIED\x10\x00\x12\x15\n\x11POWER_MODE_NORMAL\x10\x01\x12\x18\n\x14POWER_MODE_LOW_POWER\x10\x02\x12\x1a\n\x16POWER_MODE_PERFORMANCE\x10\x03\x12\x17\n\x13POWER_MODE_BALANCED\x10\x04\x32\xae\x01\n\x0cPowerService\x12L\n\x06Reboot\x12\x1e.api.gravity.v26.RebootRequest\x1a\".api.gravity.types.BooleanResponse\x12P\n\x08Shutdown\x12 .api.gravity.v26.ShutdownRequest\x1a\".api.gravity.types.BooleanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.power_service.v26.power_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POWERMODE']._serialized_start=185
  _globals['_POWERMODE']._serialized_end=326
  _globals['_REBOOTREQUEST']._serialized_start=86
  _globals['_REBOOTREQUEST']._serialized_end=132
  _globals['_SHUTDOWNREQUEST']._serialized_start=134
  _globals['_SHUTDOWNREQUEST']._serialized_end=182
  _globals['_POWERSERVICE']._serialized_start=329
  _globals['_POWERSERVICE']._serialized_end=503
# @@protoc_insertion_point(module_scope)
