"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from api.wifi_service.v26 import wifi_service_pb2 as _wifi_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class WiFiServiceStub:
    """─── Service ──────────────────────────────────────────────────────────────────"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WiFiServiceAsyncStub: ...
    ListWiFiInterfaces: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _wifi_service_pb2.WiFiInterfacesResponse]
    """Interface info"""
    GetWiFiLinkProperties: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.WiFiLinkPropertiesResponse]
    IsWiFiConnected: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]
    GetWiFiMode: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.WiFiModeResponse]
    """Mode"""
    SetWiFiMode: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.SetWiFiModeRequest, _types_pb2.BooleanResponse]
    SetAPConfig: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.APConfig, _types_pb2.BooleanResponse]
    """Access Point"""
    GetAPProperties: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.APPropertiesResponse]
    StartAP: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]
    StopAP: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]
    SetClientConfig: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.ClientConfig, _types_pb2.BooleanResponse]
    """Client"""
    GetClientProperties: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.ClientPropertiesResponse]
    Connect: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]
    Disconnect: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]
    ScanWiFi: _grpc.UnaryUnaryMultiCallable[_wifi_service_pb2.ScanWiFiRequest, _wifi_service_pb2.ScanWiFiResponse]
    """Scan"""
    SubscribeWiFiEvents: _grpc.UnaryStreamMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.WiFiLinkProperties]
    """Events"""

@_typing.type_check_only
class WiFiServiceAsyncStub(WiFiServiceStub):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    ListWiFiInterfaces: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _wifi_service_pb2.WiFiInterfacesResponse]  # type: ignore[assignment]
    """Interface info"""
    GetWiFiLinkProperties: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.WiFiLinkPropertiesResponse]  # type: ignore[assignment]
    IsWiFiConnected: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetWiFiMode: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.WiFiModeResponse]  # type: ignore[assignment]
    """Mode"""
    SetWiFiMode: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.SetWiFiModeRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    SetAPConfig: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.APConfig, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Access Point"""
    GetAPProperties: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.APPropertiesResponse]  # type: ignore[assignment]
    StartAP: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    StopAP: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    SetClientConfig: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.ClientConfig, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Client"""
    GetClientProperties: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.ClientPropertiesResponse]  # type: ignore[assignment]
    Connect: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    Disconnect: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    ScanWiFi: _aio.UnaryUnaryMultiCallable[_wifi_service_pb2.ScanWiFiRequest, _wifi_service_pb2.ScanWiFiResponse]  # type: ignore[assignment]
    """Scan"""
    SubscribeWiFiEvents: _aio.UnaryStreamMultiCallable[_wifi_service_pb2.WiFiInterfaceRequest, _wifi_service_pb2.WiFiLinkProperties]  # type: ignore[assignment]
    """Events"""

class WiFiServiceServicer(metaclass=_abc_1.ABCMeta):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    @_abc_1.abstractmethod
    def ListWiFiInterfaces(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_wifi_service_pb2.WiFiInterfacesResponse, _abc.Awaitable[_wifi_service_pb2.WiFiInterfacesResponse]]:
        """Interface info"""

    @_abc_1.abstractmethod
    def GetWiFiLinkProperties(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wifi_service_pb2.WiFiLinkPropertiesResponse, _abc.Awaitable[_wifi_service_pb2.WiFiLinkPropertiesResponse]]: ...

    @_abc_1.abstractmethod
    def IsWiFiConnected(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetWiFiMode(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wifi_service_pb2.WiFiModeResponse, _abc.Awaitable[_wifi_service_pb2.WiFiModeResponse]]:
        """Mode"""

    @_abc_1.abstractmethod
    def SetWiFiMode(
        self,
        request: _wifi_service_pb2.SetWiFiModeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def SetAPConfig(
        self,
        request: _wifi_service_pb2.APConfig,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Access Point"""

    @_abc_1.abstractmethod
    def GetAPProperties(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wifi_service_pb2.APPropertiesResponse, _abc.Awaitable[_wifi_service_pb2.APPropertiesResponse]]: ...

    @_abc_1.abstractmethod
    def StartAP(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def StopAP(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def SetClientConfig(
        self,
        request: _wifi_service_pb2.ClientConfig,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Client"""

    @_abc_1.abstractmethod
    def GetClientProperties(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wifi_service_pb2.ClientPropertiesResponse, _abc.Awaitable[_wifi_service_pb2.ClientPropertiesResponse]]: ...

    @_abc_1.abstractmethod
    def Connect(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def Disconnect(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def ScanWiFi(
        self,
        request: _wifi_service_pb2.ScanWiFiRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_wifi_service_pb2.ScanWiFiResponse, _abc.Awaitable[_wifi_service_pb2.ScanWiFiResponse]]:
        """Scan"""

    @_abc_1.abstractmethod
    def SubscribeWiFiEvents(
        self,
        request: _wifi_service_pb2.WiFiInterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_wifi_service_pb2.WiFiLinkProperties], _abc.AsyncIterator[_wifi_service_pb2.WiFiLinkProperties]]:
        """Events"""

def add_WiFiServiceServicer_to_server(servicer: WiFiServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
