"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.auth_service.v26 import auth_service_pb2 as _auth_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AuthServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AuthServiceAsyncStub: ...
    Login: _grpc.UnaryUnaryMultiCallable[_auth_service_pb2.LoginRequest, _auth_service_pb2.LoginResponse]
    Logout: _grpc.UnaryUnaryMultiCallable[_auth_service_pb2.LogoutRequest, _auth_service_pb2.LogoutResponse]

@_typing.type_check_only
class AuthServiceAsyncStub(AuthServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Login: _aio.UnaryUnaryMultiCallable[_auth_service_pb2.LoginRequest, _auth_service_pb2.LoginResponse]  # type: ignore[assignment]
    Logout: _aio.UnaryUnaryMultiCallable[_auth_service_pb2.LogoutRequest, _auth_service_pb2.LogoutResponse]  # type: ignore[assignment]

class AuthServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Login(
        self,
        request: _auth_service_pb2.LoginRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_service_pb2.LoginResponse, _abc.Awaitable[_auth_service_pb2.LoginResponse]]: ...

    @_abc_1.abstractmethod
    def Logout(
        self,
        request: _auth_service_pb2.LogoutRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_service_pb2.LogoutResponse, _abc.Awaitable[_auth_service_pb2.LogoutResponse]]: ...

def add_AuthServiceServicer_to_server(servicer: AuthServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
