# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.common import types_pb2 as api_dot_common_dot_types__pb2
from api.system_service.v26 import system_service_pb2 as api_dot_system__service_dot_v26_dot_system__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/system_service/v26/system_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetApiVersion = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetApiVersion',
                request_serializer=api_dot_common_dot_types__pb2.Void.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.APIVersionResponse.FromString,
                _registered_method=True)
        self.GetApiVersionInfo = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetApiVersionInfo',
                request_serializer=api_dot_common_dot_types__pb2.Void.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetDeviceName = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetDeviceName',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetSocModel = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetSocModel',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetSocVendor = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetSocVendor',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetBoardModel = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetBoardModel',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetBoardVendor = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetBoardVendor',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetHardwareVersion = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetHardwareVersion',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetHardwareModel = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetHardwareModel',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetSystemUuid = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetSystemUuid',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetBoardSerial = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetBoardSerial',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetCpuSerial = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetCpuSerial',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetMachineId = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetMachineId',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetArchitecture = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetArchitecture',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetTotalRAM = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetTotalRAM',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.UInt64Response.FromString,
                _registered_method=True)
        self.GetCpuModel = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetCpuModel',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetCpuCores = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetCpuCores',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.GetCpuThreads = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetCpuThreads',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.GetCpuMinMhz = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetCpuMinMhz',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.DoubleResponse.FromString,
                _registered_method=True)
        self.GetCpuMaxMhz = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetCpuMaxMhz',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.DoubleResponse.FromString,
                _registered_method=True)
        self.GetOsName = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetOsName',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetOsVersion = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetOsVersion',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetOsRevision = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetOsRevision',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetRuntimeVersion = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetRuntimeVersion',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetRuntimeBuildDate = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetRuntimeBuildDate',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetDistro = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetDistro',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetDistroVersion = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetDistroVersion',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetKernelVersion = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetKernelVersion',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/api.gravity.v26.SystemService/GetMetrics',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_system__service_dot_v26_dot_system__service__pb2.MetricsInfoResponse.FromString,
                _registered_method=True)
        self.AllowUntrustedApps = channel.unary_unary(
                '/api.gravity.v26.SystemService/AllowUntrustedApps',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisallowUntrustedApps = channel.unary_unary(
                '/api.gravity.v26.SystemService/DisallowUntrustedApps',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.IsUntrustedAppsAllowed = channel.unary_unary(
                '/api.gravity.v26.SystemService/IsUntrustedAppsAllowed',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.EnableRebootOnFailure = channel.unary_unary(
                '/api.gravity.v26.SystemService/EnableRebootOnFailure',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisableRebootOnFailure = channel.unary_unary(
                '/api.gravity.v26.SystemService/DisableRebootOnFailure',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.IsRebootOnFailureEnabled = channel.unary_unary(
                '/api.gravity.v26.SystemService/IsRebootOnFailureEnabled',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.EnableDeveMode = channel.unary_unary(
                '/api.gravity.v26.SystemService/EnableDeveMode',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisableDevMode = channel.unary_unary(
                '/api.gravity.v26.SystemService/DisableDevMode',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.IsDevModeEnabled = channel.unary_unary(
                '/api.gravity.v26.SystemService/IsDevModeEnabled',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.EnableSSHServer = channel.unary_unary(
                '/api.gravity.v26.SystemService/EnableSSHServer',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisableSSHServer = channel.unary_unary(
                '/api.gravity.v26.SystemService/DisableSSHServer',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.IsSSHServerEnabled = channel.unary_unary(
                '/api.gravity.v26.SystemService/IsSSHServerEnabled',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.Attach = channel.unary_unary(
                '/api.gravity.v26.SystemService/Attach',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetApiVersion(self, request, context):
        """Get API Version and Revision
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiVersionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceName(self, request, context):
        """Returns the user-friendly device name (e.g., hostname or descriptive identifier)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocVendor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoardModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoardVendor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemUuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoardSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCpuSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArchitecture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalRAM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCpuModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCpuCores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCpuThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCpuMinMhz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCpuMaxMhz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOsName(self, request, context):
        """Logic OS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOsVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOsRevision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeVersion(self, request, context):
        """Runtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeBuildDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistro(self, request, context):
        """Linux Distro
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistroVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKernelVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """System Metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllowUntrustedApps(self, request, context):
        """Untrusted apps installation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisallowUntrustedApps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsUntrustedAppsAllowed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableRebootOnFailure(self, request, context):
        """Reboot on failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableRebootOnFailure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsRebootOnFailureEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableDeveMode(self, request, context):
        """Development mode enable/disable
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableDevMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsDevModeEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableSSHServer(self, request, context):
        """SSH Server enable/disable
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableSSHServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsSSHServerEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attach(self, request, context):
        """Attach — mandatory environment binding call.
        Every app must call this within the launch timeout or Gravity kills the process.
        Allowed for any installed app regardless of permissions declared in identity.json.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetApiVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiVersion,
                    request_deserializer=api_dot_common_dot_types__pb2.Void.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.APIVersionResponse.SerializeToString,
            ),
            'GetApiVersionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiVersionInfo,
                    request_deserializer=api_dot_common_dot_types__pb2.Void.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetDeviceName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceName,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetSocModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocModel,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetSocVendor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocVendor,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetBoardModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoardModel,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetBoardVendor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoardVendor,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetHardwareVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareVersion,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetHardwareModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareModel,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetSystemUuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemUuid,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetBoardSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoardSerial,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetCpuSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuSerial,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetMachineId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineId,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetArchitecture': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArchitecture,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetTotalRAM': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalRAM,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.UInt64Response.SerializeToString,
            ),
            'GetCpuModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuModel,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetCpuCores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuCores,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.IntegerResponse.SerializeToString,
            ),
            'GetCpuThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuThreads,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.IntegerResponse.SerializeToString,
            ),
            'GetCpuMinMhz': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuMinMhz,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.DoubleResponse.SerializeToString,
            ),
            'GetCpuMaxMhz': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCpuMaxMhz,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.DoubleResponse.SerializeToString,
            ),
            'GetOsName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOsName,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetOsVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOsVersion,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetOsRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOsRevision,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetRuntimeVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeVersion,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetRuntimeBuildDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeBuildDate,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetDistro': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistro,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetDistroVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistroVersion,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetKernelVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKernelVersion,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_system__service_dot_v26_dot_system__service__pb2.MetricsInfoResponse.SerializeToString,
            ),
            'AllowUntrustedApps': grpc.unary_unary_rpc_method_handler(
                    servicer.AllowUntrustedApps,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisallowUntrustedApps': grpc.unary_unary_rpc_method_handler(
                    servicer.DisallowUntrustedApps,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'IsUntrustedAppsAllowed': grpc.unary_unary_rpc_method_handler(
                    servicer.IsUntrustedAppsAllowed,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'EnableRebootOnFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableRebootOnFailure,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisableRebootOnFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableRebootOnFailure,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'IsRebootOnFailureEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsRebootOnFailureEnabled,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'EnableDeveMode': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableDeveMode,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisableDevMode': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableDevMode,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'IsDevModeEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsDevModeEnabled,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'EnableSSHServer': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableSSHServer,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisableSSHServer': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableSSHServer,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'IsSSHServerEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSSHServerEnabled,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'Attach': grpc.unary_unary_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetApiVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetApiVersion',
            api_dot_common_dot_types__pb2.Void.SerializeToString,
            api_dot_common_dot_types__pb2.APIVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApiVersionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetApiVersionInfo',
            api_dot_common_dot_types__pb2.Void.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetDeviceName',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSocModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetSocModel',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSocVendor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetSocVendor',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoardModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetBoardModel',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoardVendor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetBoardVendor',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetHardwareVersion',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetHardwareModel',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemUuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetSystemUuid',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoardSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetBoardSerial',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCpuSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetCpuSerial',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetMachineId',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArchitecture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetArchitecture',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalRAM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetTotalRAM',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.UInt64Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCpuModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetCpuModel',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCpuCores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetCpuCores',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCpuThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetCpuThreads',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCpuMinMhz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetCpuMinMhz',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.DoubleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCpuMaxMhz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetCpuMaxMhz',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.DoubleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOsName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetOsName',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOsVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetOsVersion',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOsRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetOsRevision',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetRuntimeVersion',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeBuildDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetRuntimeBuildDate',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetDistro',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistroVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetDistroVersion',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKernelVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetKernelVersion',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/GetMetrics',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_system__service_dot_v26_dot_system__service__pb2.MetricsInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllowUntrustedApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/AllowUntrustedApps',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisallowUntrustedApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/DisallowUntrustedApps',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsUntrustedAppsAllowed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/IsUntrustedAppsAllowed',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableRebootOnFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/EnableRebootOnFailure',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableRebootOnFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/DisableRebootOnFailure',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsRebootOnFailureEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/IsRebootOnFailureEnabled',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableDeveMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/EnableDeveMode',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableDevMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/DisableDevMode',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsDevModeEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/IsDevModeEnabled',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableSSHServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/EnableSSHServer',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableSSHServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/DisableSSHServer',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsSSHServerEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/IsSSHServerEnabled',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.SystemService/Attach',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
