"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _APIVersionInfo:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _APIVersionInfoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_APIVersionInfo.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VERSION_INIT: _APIVersionInfo.ValueType  # 0
    VERSION: _APIVersionInfo.ValueType  # 26

class APIVersionInfo(_APIVersionInfo, metaclass=_APIVersionInfoEnumTypeWrapper): ...

VERSION_INIT: APIVersionInfo.ValueType  # 0
VERSION: APIVersionInfo.ValueType  # 26
Global___APIVersionInfo: _TypeAlias = APIVersionInfo  # noqa: Y015

class _APIRevisionInfo:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _APIRevisionInfoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_APIRevisionInfo.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REVISION: _APIRevisionInfo.ValueType  # 0

class APIRevisionInfo(_APIRevisionInfo, metaclass=_APIRevisionInfoEnumTypeWrapper): ...

REVISION: APIRevisionInfo.ValueType  # 0
Global___APIRevisionInfo: _TypeAlias = APIRevisionInfo  # noqa: Y015

@_typing.final
class MetricsInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SysUptime(_message.Message):
        """Mensagens aninhadas"""

        DESCRIPTOR: _descriptor.Descriptor

        TIME_FIELD_NUMBER: _builtins.int
        UPTIME_FIELD_NUMBER: _builtins.int
        USERS_FIELD_NUMBER: _builtins.int
        LOAD_AVERAGE_FIELD_NUMBER: _builtins.int
        time: _builtins.str
        uptime: _builtins.int
        """em segundos"""
        users: _builtins.int
        @_builtins.property
        def load_average(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
            """1min, 5min, 15min"""

        def __init__(
            self,
            *,
            time: _builtins.str = ...,
            uptime: _builtins.int = ...,
            users: _builtins.int = ...,
            load_average: _abc.Iterable[_builtins.float] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["load_average", b"load_average", "time", b"time", "uptime", b"uptime", "users", b"users"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CpuStats(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CTX_SWITCHES_FIELD_NUMBER: _builtins.int
        INTERRUPTS_FIELD_NUMBER: _builtins.int
        SOFT_INTERRUPTS_FIELD_NUMBER: _builtins.int
        SYSCALLS_FIELD_NUMBER: _builtins.int
        ctx_switches: _builtins.int
        interrupts: _builtins.int
        soft_interrupts: _builtins.int
        syscalls: _builtins.int
        def __init__(
            self,
            *,
            ctx_switches: _builtins.int = ...,
            interrupts: _builtins.int = ...,
            soft_interrupts: _builtins.int = ...,
            syscalls: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["ctx_switches", b"ctx_switches", "interrupts", b"interrupts", "soft_interrupts", b"soft_interrupts", "syscalls", b"syscalls"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CpuFreq(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CURRENT_FIELD_NUMBER: _builtins.int
        MIN_FIELD_NUMBER: _builtins.int
        MAX_FIELD_NUMBER: _builtins.int
        current: _builtins.float
        """MHz"""
        min: _builtins.float
        """MHz"""
        max: _builtins.float
        """MHz"""
        def __init__(
            self,
            *,
            current: _builtins.float = ...,
            min: _builtins.float = ...,
            max: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["current", b"current", "max", b"max", "min", b"min"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class VirtualMemory(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOTAL_FIELD_NUMBER: _builtins.int
        AVAILABLE_FIELD_NUMBER: _builtins.int
        PERCENT_FIELD_NUMBER: _builtins.int
        USED_FIELD_NUMBER: _builtins.int
        FREE_FIELD_NUMBER: _builtins.int
        ACTIVE_FIELD_NUMBER: _builtins.int
        INACTIVE_FIELD_NUMBER: _builtins.int
        BUFFERS_FIELD_NUMBER: _builtins.int
        CACHED_FIELD_NUMBER: _builtins.int
        SHARED_FIELD_NUMBER: _builtins.int
        SLAB_FIELD_NUMBER: _builtins.int
        total: _builtins.int
        """bytes"""
        available: _builtins.int
        """bytes"""
        percent: _builtins.float
        """percentagem"""
        used: _builtins.int
        """bytes"""
        free: _builtins.int
        """bytes"""
        active: _builtins.int
        """bytes"""
        inactive: _builtins.int
        """bytes"""
        buffers: _builtins.int
        """bytes"""
        cached: _builtins.int
        """bytes"""
        shared: _builtins.int
        """bytes"""
        slab: _builtins.int
        """bytes"""
        def __init__(
            self,
            *,
            total: _builtins.int = ...,
            available: _builtins.int = ...,
            percent: _builtins.float = ...,
            used: _builtins.int = ...,
            free: _builtins.int = ...,
            active: _builtins.int = ...,
            inactive: _builtins.int = ...,
            buffers: _builtins.int = ...,
            cached: _builtins.int = ...,
            shared: _builtins.int = ...,
            slab: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "available", b"available", "buffers", b"buffers", "cached", b"cached", "free", b"free", "inactive", b"inactive", "percent", b"percent", "shared", b"shared", "slab", b"slab", "total", b"total", "used", b"used"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DiskUsage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOTAL_FIELD_NUMBER: _builtins.int
        USED_FIELD_NUMBER: _builtins.int
        FREE_FIELD_NUMBER: _builtins.int
        PERCENT_FIELD_NUMBER: _builtins.int
        total: _builtins.int
        """bytes"""
        used: _builtins.int
        """bytes"""
        free: _builtins.int
        """bytes"""
        percent: _builtins.float
        """percentagem"""
        def __init__(
            self,
            *,
            total: _builtins.int = ...,
            used: _builtins.int = ...,
            free: _builtins.int = ...,
            percent: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["free", b"free", "percent", b"percent", "total", b"total", "used", b"used"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DiskIoCounters(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        READ_COUNT_FIELD_NUMBER: _builtins.int
        WRITE_COUNT_FIELD_NUMBER: _builtins.int
        READ_BYTES_FIELD_NUMBER: _builtins.int
        WRITE_BYTES_FIELD_NUMBER: _builtins.int
        READ_TIME_FIELD_NUMBER: _builtins.int
        WRITE_TIME_FIELD_NUMBER: _builtins.int
        READ_MERGED_COUNT_FIELD_NUMBER: _builtins.int
        WRITE_MERGED_COUNT_FIELD_NUMBER: _builtins.int
        BUSY_TIME_FIELD_NUMBER: _builtins.int
        read_count: _builtins.int
        write_count: _builtins.int
        read_bytes: _builtins.int
        write_bytes: _builtins.int
        read_time: _builtins.int
        write_time: _builtins.int
        read_merged_count: _builtins.int
        write_merged_count: _builtins.int
        busy_time: _builtins.int
        def __init__(
            self,
            *,
            read_count: _builtins.int = ...,
            write_count: _builtins.int = ...,
            read_bytes: _builtins.int = ...,
            write_bytes: _builtins.int = ...,
            read_time: _builtins.int = ...,
            write_time: _builtins.int = ...,
            read_merged_count: _builtins.int = ...,
            write_merged_count: _builtins.int = ...,
            busy_time: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["busy_time", b"busy_time", "read_bytes", b"read_bytes", "read_count", b"read_count", "read_merged_count", b"read_merged_count", "read_time", b"read_time", "write_bytes", b"write_bytes", "write_count", b"write_count", "write_merged_count", b"write_merged_count", "write_time", b"write_time"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Network(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        BYTES_SENT_FIELD_NUMBER: _builtins.int
        BYTES_RECV_FIELD_NUMBER: _builtins.int
        PACKETS_SENT_FIELD_NUMBER: _builtins.int
        PACKETS_RECV_FIELD_NUMBER: _builtins.int
        ERRIN_FIELD_NUMBER: _builtins.int
        ERROUT_FIELD_NUMBER: _builtins.int
        DROPIN_FIELD_NUMBER: _builtins.int
        DROPOUT_FIELD_NUMBER: _builtins.int
        bytes_sent: _builtins.int
        bytes_recv: _builtins.int
        packets_sent: _builtins.int
        packets_recv: _builtins.int
        errin: _builtins.int
        errout: _builtins.int
        dropin: _builtins.int
        dropout: _builtins.int
        def __init__(
            self,
            *,
            bytes_sent: _builtins.int = ...,
            bytes_recv: _builtins.int = ...,
            packets_sent: _builtins.int = ...,
            packets_recv: _builtins.int = ...,
            errin: _builtins.int = ...,
            errout: _builtins.int = ...,
            dropin: _builtins.int = ...,
            dropout: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_recv", b"bytes_recv", "bytes_sent", b"bytes_sent", "dropin", b"dropin", "dropout", b"dropout", "errin", b"errin", "errout", b"errout", "packets_recv", b"packets_recv", "packets_sent", b"packets_sent"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DiskUsageEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___MetricsInfo.DiskUsage: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___MetricsInfo.DiskUsage | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SYS_UPTIME_FIELD_NUMBER: _builtins.int
    CPU_USAGE_FIELD_NUMBER: _builtins.int
    CPU_CORE_PERCENT_FIELD_NUMBER: _builtins.int
    MEMORY_USAGE_FIELD_NUMBER: _builtins.int
    SOC_THERMAL_FIELD_NUMBER: _builtins.int
    CPU_STATS_FIELD_NUMBER: _builtins.int
    CPU_FREQ_FIELD_NUMBER: _builtins.int
    VIRTUAL_MEMORY_FIELD_NUMBER: _builtins.int
    DISK_USAGE_FIELD_NUMBER: _builtins.int
    DISK_IO_COUNTERS_FIELD_NUMBER: _builtins.int
    NETWORK_FIELD_NUMBER: _builtins.int
    SENSORS_TEMPERATURES_FIELD_NUMBER: _builtins.int
    cpu_usage: _builtins.float
    memory_usage: _builtins.float
    soc_thermal: _builtins.float
    sensors_temperatures: _builtins.int
    @_builtins.property
    def sys_uptime(self) -> Global___MetricsInfo.SysUptime:
        """Campos da mensagem Metrics"""

    @_builtins.property
    def cpu_core_percent(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def cpu_stats(self) -> Global___MetricsInfo.CpuStats: ...
    @_builtins.property
    def cpu_freq(self) -> Global___MetricsInfo.CpuFreq: ...
    @_builtins.property
    def virtual_memory(self) -> Global___MetricsInfo.VirtualMemory: ...
    @_builtins.property
    def disk_usage(self) -> _containers.MessageMap[_builtins.str, Global___MetricsInfo.DiskUsage]: ...
    @_builtins.property
    def disk_io_counters(self) -> Global___MetricsInfo.DiskIoCounters: ...
    @_builtins.property
    def network(self) -> Global___MetricsInfo.Network: ...
    def __init__(
        self,
        *,
        sys_uptime: Global___MetricsInfo.SysUptime | None = ...,
        cpu_usage: _builtins.float = ...,
        cpu_core_percent: _abc.Iterable[_builtins.float] | None = ...,
        memory_usage: _builtins.float = ...,
        soc_thermal: _builtins.float = ...,
        cpu_stats: Global___MetricsInfo.CpuStats | None = ...,
        cpu_freq: Global___MetricsInfo.CpuFreq | None = ...,
        virtual_memory: Global___MetricsInfo.VirtualMemory | None = ...,
        disk_usage: _abc.Mapping[_builtins.str, Global___MetricsInfo.DiskUsage] | None = ...,
        disk_io_counters: Global___MetricsInfo.DiskIoCounters | None = ...,
        network: Global___MetricsInfo.Network | None = ...,
        sensors_temperatures: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cpu_freq", b"cpu_freq", "cpu_stats", b"cpu_stats", "disk_io_counters", b"disk_io_counters", "network", b"network", "sys_uptime", b"sys_uptime", "virtual_memory", b"virtual_memory"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cpu_core_percent", b"cpu_core_percent", "cpu_freq", b"cpu_freq", "cpu_stats", b"cpu_stats", "cpu_usage", b"cpu_usage", "disk_io_counters", b"disk_io_counters", "disk_usage", b"disk_usage", "memory_usage", b"memory_usage", "network", b"network", "sensors_temperatures", b"sensors_temperatures", "soc_thermal", b"soc_thermal", "sys_uptime", b"sys_uptime", "virtual_memory", b"virtual_memory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetricsInfo: _TypeAlias = MetricsInfo  # noqa: Y015

@_typing.final
class MetricsInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    METRICS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def metrics(self) -> Global___MetricsInfo: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        metrics: Global___MetricsInfo | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "metrics", b"metrics"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "metrics", b"metrics"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetricsInfoResponse: _TypeAlias = MetricsInfoResponse  # noqa: Y015
