# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/pwm_service/v26/pwm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/pwm_service/v26/pwm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import types_pb2 as api_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%api/pwm_service/v26/pwm_service.proto\x12\x0f\x61pi.gravity.v26\x1a\x16\x61pi/common/types.proto\"+\n\nPwmChannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"x\n\rPwmProperties\x12,\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x1b.api.gravity.v26.PwmChannel\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x12\n\nduty_cycle\x18\x03 \x01(\x01\x12\x14\n\x0c\x66requency_hz\x18\x04 \x01(\x01\"A\n\x11PwmChannelRequest\x12,\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x1b.api.gravity.v26.PwmChannel\"g\n\rSetPwmRequest\x12,\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x1b.api.gravity.v26.PwmChannel\x12\x12\n\nduty_cycle\x18\x02 \x01(\x01\x12\x14\n\x0c\x66requency_hz\x18\x03 \x01(\x01\"q\n\x13PwmChannelsResponse\x12-\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x1b.api.gravity.v26.PwmChannel\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1c.api.gravity.types.ErrorInfo\"x\n\x15PwmPropertiesResponse\x12\x32\n\nproperties\x18\x01 \x01(\x0b\x32\x1e.api.gravity.v26.PwmProperties\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1c.api.gravity.types.ErrorInfo2\xe0\x02\n\nPwmService\x12Q\n\x0fListPwmChannels\x12\x18.api.gravity.types.Empty\x1a$.api.gravity.v26.PwmChannelsResponse\x12^\n\x10GetPwmProperties\x12\".api.gravity.v26.PwmChannelRequest\x1a&.api.gravity.v26.PwmPropertiesResponse\x12L\n\x06SetPwm\x12\x1e.api.gravity.v26.SetPwmRequest\x1a\".api.gravity.types.BooleanResponse\x12Q\n\x07StopPwm\x12\".api.gravity.v26.PwmChannelRequest\x1a\".api.gravity.types.BooleanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.pwm_service.v26.pwm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PWMCHANNEL']._serialized_start=82
  _globals['_PWMCHANNEL']._serialized_end=125
  _globals['_PWMPROPERTIES']._serialized_start=127
  _globals['_PWMPROPERTIES']._serialized_end=247
  _globals['_PWMCHANNELREQUEST']._serialized_start=249
  _globals['_PWMCHANNELREQUEST']._serialized_end=314
  _globals['_SETPWMREQUEST']._serialized_start=316
  _globals['_SETPWMREQUEST']._serialized_end=419
  _globals['_PWMCHANNELSRESPONSE']._serialized_start=421
  _globals['_PWMCHANNELSRESPONSE']._serialized_end=534
  _globals['_PWMPROPERTIESRESPONSE']._serialized_start=536
  _globals['_PWMPROPERTIESRESPONSE']._serialized_end=656
  _globals['_PWMSERVICE']._serialized_start=659
  _globals['_PWMSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
