"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PwmChannel(_message.Message):
    """─── Properties Messages ──────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    channel: _builtins.int
    """Hardware channel index"""
    name: _builtins.str
    """Human-readable name (e.g. "pwm0")"""
    def __init__(
        self,
        *,
        channel: _builtins.int = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PwmChannel: _TypeAlias = PwmChannel  # noqa: Y015

@_typing.final
class PwmProperties(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    DUTY_CYCLE_FIELD_NUMBER: _builtins.int
    FREQUENCY_HZ_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    duty_cycle: _builtins.float
    """0.0 – 1.0"""
    frequency_hz: _builtins.float
    """e.g. 1000"""
    @_builtins.property
    def channel(self) -> Global___PwmChannel: ...
    def __init__(
        self,
        *,
        channel: Global___PwmChannel | None = ...,
        enabled: _builtins.bool = ...,
        duty_cycle: _builtins.float = ...,
        frequency_hz: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "duty_cycle", b"duty_cycle", "enabled", b"enabled", "frequency_hz", b"frequency_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PwmProperties: _TypeAlias = PwmProperties  # noqa: Y015

@_typing.final
class PwmChannelRequest(_message.Message):
    """─── Request Messages ─────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def channel(self) -> Global___PwmChannel: ...
    def __init__(
        self,
        *,
        channel: Global___PwmChannel | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PwmChannelRequest: _TypeAlias = PwmChannelRequest  # noqa: Y015

@_typing.final
class SetPwmRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: _builtins.int
    DUTY_CYCLE_FIELD_NUMBER: _builtins.int
    FREQUENCY_HZ_FIELD_NUMBER: _builtins.int
    duty_cycle: _builtins.float
    """0.0 – 1.0"""
    frequency_hz: _builtins.float
    """e.g. 1000"""
    @_builtins.property
    def channel(self) -> Global___PwmChannel: ...
    def __init__(
        self,
        *,
        channel: Global___PwmChannel | None = ...,
        duty_cycle: _builtins.float = ...,
        frequency_hz: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "duty_cycle", b"duty_cycle", "frequency_hz", b"frequency_hz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetPwmRequest: _TypeAlias = SetPwmRequest  # noqa: Y015

@_typing.final
class PwmChannelsResponse(_message.Message):
    """─── Response Messages ────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def channels(self) -> _containers.RepeatedCompositeFieldContainer[Global___PwmChannel]: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        channels: _abc.Iterable[Global___PwmChannel] | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PwmChannelsResponse: _TypeAlias = PwmChannelsResponse  # noqa: Y015

@_typing.final
class PwmPropertiesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROPERTIES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def properties(self) -> Global___PwmProperties: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        properties: Global___PwmProperties | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "properties", b"properties"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "properties", b"properties"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PwmPropertiesResponse: _TypeAlias = PwmPropertiesResponse  # noqa: Y015
