# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.common import types_pb2 as api_dot_common_dot_types__pb2
from api.vpn_service.v26 import vpn_service_pb2 as api_dot_vpn__service_dot_v26_dot_vpn__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/vpn_service/v26/vpn_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VPNServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/api.gravity.v26.VPNService/GetCapabilities',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ListProfiles = channel.unary_unary(
                '/api.gravity.v26.VPNService/ListProfiles',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfilesResponse.FromString,
                _registered_method=True)
        self.ApplyProfile = channel.unary_unary(
                '/api.gravity.v26.VPNService/ApplyProfile',
                request_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ApplyProfileRequest.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ApplyProfileResponse.FromString,
                _registered_method=True)
        self.RemoveProfile = channel.unary_unary(
                '/api.gravity.v26.VPNService/RemoveProfile',
                request_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/api.gravity.v26.VPNService/Connect',
                request_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/api.gravity.v26.VPNService/Disconnect',
                request_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/api.gravity.v26.VPNService/GetStatus',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/api.gravity.v26.VPNService/ListSessions',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.SessionsResponse.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/api.gravity.v26.VPNService/WatchEvents',
                request_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VPNEvent.FromString,
                _registered_method=True)


class VPNServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    """

    def GetCapabilities(self, request, context):
        """Capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfiles(self, request, context):
        """Profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VPNServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnCapabilitiesResponse.SerializeToString,
            ),
            'ListProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfiles,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfilesResponse.SerializeToString,
            ),
            'ApplyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyProfile,
                    request_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ApplyProfileRequest.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ApplyProfileResponse.SerializeToString,
            ),
            'RemoveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProfile,
                    request_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.GetStatusResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.SessionsResponse.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.WatchEventsRequest.FromString,
                    response_serializer=api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VPNEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.VPNService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.VPNService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VPNService(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/GetCapabilities',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/ListProfiles',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/ApplyProfile',
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ApplyProfileRequest.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ApplyProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/RemoveProfile',
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/Connect',
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/Disconnect',
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VpnProfileRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/GetStatus',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.VPNService/ListSessions',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.SessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.VPNService/WatchEvents',
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.WatchEventsRequest.SerializeToString,
            api_dot_vpn__service_dot_v26_dot_vpn__service__pb2.VPNEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
