"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CapabilitiesResponse(_message.Message):
    """Response for GetCapabilities"""

    DESCRIPTOR: _descriptor.Descriptor

    SENSOR_TYPES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sensor_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """List of available sensor types (ex: ["cpu-thermal", "accelerometer", "gyroscope"])"""

    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        sensor_types: _abc.Iterable[_builtins.str] | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "sensor_types", b"sensor_types"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CapabilitiesResponse: _TypeAlias = CapabilitiesResponse  # noqa: Y015

@_typing.final
class SensorEventsRequest(_message.Message):
    """Request for SubscribeSensorEvents"""

    DESCRIPTOR: _descriptor.Descriptor

    SENSOR_TYPES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sensor_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Optional: filter by sensor type (empty = all)
        Examples: "cpu-thermal", "accelerometer", "gyroscope", etc.
        """

    def __init__(
        self,
        *,
        sensor_types: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sensor_types", b"sensor_types"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SensorEventsRequest: _TypeAlias = SensorEventsRequest  # noqa: Y015

@_typing.final
class SensorEventResponse(_message.Message):
    """Response for sensor events"""

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def event(self) -> Global___SensorEvent: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        event: Global___SensorEvent | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "event", b"event"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "event", b"event"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SensorEventResponse: _TypeAlias = SensorEventResponse  # noqa: Y015

@_typing.final
class SensorEvent(_message.Message):
    """Sensor event"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SENSOR_TYPE_FIELD_NUMBER: _builtins.int
    SENSOR_NAME_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.int
    """Event timestamp (Unix timestamp in milliseconds)"""
    sensor_type: _builtins.str
    """Sensor type (ex: "cpu-thermal", "accelerometer", "gyroscope", "temperature")"""
    sensor_name: _builtins.str
    """Sensor name/identifier (ex: "thermal_zone0", "accel_0", "imu_1")"""
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Array of sensor values (generic)
        Examples:
        - Temperature: [45.2]
        - Accelerometer: [1.2, 3.4, 5.6] (x, y, z)
        - Multiple temperatures: [45.2, 50.1, 48.3]
        """

    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Metadata describing how to interpret the values
        Examples:
        - Temperature: {"format": "[ºC]", "unit": "celsius"}
        - Accelerometer: {"format": "[x,y,z]", "unit": "m/s²"}
        - Multiple temperatures: {"format": "[thermal_zone0,thermal_zone1,thermal_zone2]", "unit": "ºC"}
        - Gyroscope: {"format": "[roll,pitch,yaw]", "unit": "rad/s"}
        """

    def __init__(
        self,
        *,
        timestamp: _builtins.int = ...,
        sensor_type: _builtins.str = ...,
        sensor_name: _builtins.str = ...,
        values: _abc.Iterable[_builtins.float] | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "sensor_name", b"sensor_name", "sensor_type", b"sensor_type", "timestamp", b"timestamp", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SensorEvent: _TypeAlias = SensorEvent  # noqa: Y015
