"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ZonePolicy:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ZonePolicyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ZonePolicy.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    POLICY_ACCEPT: _ZonePolicy.ValueType  # 0
    POLICY_DROP: _ZonePolicy.ValueType  # 1
    POLICY_REJECT: _ZonePolicy.ValueType  # 2

class ZonePolicy(_ZonePolicy, metaclass=_ZonePolicyEnumTypeWrapper):
    """─── Enums ───────────────────────────────────────────────────────────────────"""

POLICY_ACCEPT: ZonePolicy.ValueType  # 0
POLICY_DROP: ZonePolicy.ValueType  # 1
POLICY_REJECT: ZonePolicy.ValueType  # 2
Global___ZonePolicy: _TypeAlias = ZonePolicy  # noqa: Y015

class _FirewallProtocol:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FirewallProtocolEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FirewallProtocol.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PROTO_ANY: _FirewallProtocol.ValueType  # 0
    PROTO_TCP: _FirewallProtocol.ValueType  # 1
    PROTO_UDP: _FirewallProtocol.ValueType  # 2
    PROTO_ICMP: _FirewallProtocol.ValueType  # 3

class FirewallProtocol(_FirewallProtocol, metaclass=_FirewallProtocolEnumTypeWrapper): ...

PROTO_ANY: FirewallProtocol.ValueType  # 0
PROTO_TCP: FirewallProtocol.ValueType  # 1
PROTO_UDP: FirewallProtocol.ValueType  # 2
PROTO_ICMP: FirewallProtocol.ValueType  # 3
Global___FirewallProtocol: _TypeAlias = FirewallProtocol  # noqa: Y015

@_typing.final
class ZoneRequest(_message.Message):
    """─── Zones ───────────────────────────────────────────────────────────────────

    Zona = interface(s) + política de entrada/saída
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    INTERFACES_FIELD_NUMBER: _builtins.int
    INPUT_POLICY_FIELD_NUMBER: _builtins.int
    OUTPUT_POLICY_FIELD_NUMBER: _builtins.int
    MASQUERADE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """ex: "lan", "wan" """
    input_policy: Global___ZonePolicy.ValueType
    output_policy: Global___ZonePolicy.ValueType
    masquerade: _builtins.bool
    """NAT (tipicamente só na wan)"""
    @_builtins.property
    def interfaces(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """ex: ["eth0", "wlan0"]"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        interfaces: _abc.Iterable[_builtins.str] | None = ...,
        input_policy: Global___ZonePolicy.ValueType = ...,
        output_policy: Global___ZonePolicy.ValueType = ...,
        masquerade: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input_policy", b"input_policy", "interfaces", b"interfaces", "masquerade", b"masquerade", "name", b"name", "output_policy", b"output_policy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ZoneRequest: _TypeAlias = ZoneRequest  # noqa: Y015

@_typing.final
class ZoneNameRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ZoneNameRequest: _TypeAlias = ZoneNameRequest  # noqa: Y015

@_typing.final
class ZonesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ZONES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def zones(self) -> _containers.RepeatedCompositeFieldContainer[Global___ZoneRequest]: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        zones: _abc.Iterable[Global___ZoneRequest] | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "zones", b"zones"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ZonesResponse: _TypeAlias = ZonesResponse  # noqa: Y015

@_typing.final
class FirewallRuleRequest(_message.Message):
    """─── Rules ───────────────────────────────────────────────────────────────────

    Regra = exceção pontual à política da zona (ex: abrir porta 22 na wan)
    """

    DESCRIPTOR: _descriptor.Descriptor

    SRC_ZONE_FIELD_NUMBER: _builtins.int
    DST_ZONE_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    SRC_IP_FIELD_NUMBER: _builtins.int
    DEST_PORT_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    src_zone: _builtins.str
    """zona origem (vazio = qualquer)"""
    dst_zone: _builtins.str
    """zona destino (vazio = qualquer)"""
    protocol: Global___FirewallProtocol.ValueType
    src_ip: _builtins.str
    """CIDR ex: "192.168.1.0/24" (vazio = qualquer)"""
    dest_port: _builtins.int
    """0 = qualquer"""
    action: Global___ZonePolicy.ValueType
    comment: _builtins.str
    def __init__(
        self,
        *,
        src_zone: _builtins.str = ...,
        dst_zone: _builtins.str = ...,
        protocol: Global___FirewallProtocol.ValueType = ...,
        src_ip: _builtins.str = ...,
        dest_port: _builtins.int = ...,
        action: Global___ZonePolicy.ValueType = ...,
        comment: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "comment", b"comment", "dest_port", b"dest_port", "dst_zone", b"dst_zone", "protocol", b"protocol", "src_ip", b"src_ip", "src_zone", b"src_zone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FirewallRuleRequest: _TypeAlias = FirewallRuleRequest  # noqa: Y015

@_typing.final
class FirewallRule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SRC_ZONE_FIELD_NUMBER: _builtins.int
    DST_ZONE_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    SRC_IP_FIELD_NUMBER: _builtins.int
    DEST_PORT_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """gerado pelo servidor"""
    src_zone: _builtins.str
    dst_zone: _builtins.str
    protocol: Global___FirewallProtocol.ValueType
    src_ip: _builtins.str
    dest_port: _builtins.int
    action: Global___ZonePolicy.ValueType
    comment: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        src_zone: _builtins.str = ...,
        dst_zone: _builtins.str = ...,
        protocol: Global___FirewallProtocol.ValueType = ...,
        src_ip: _builtins.str = ...,
        dest_port: _builtins.int = ...,
        action: Global___ZonePolicy.ValueType = ...,
        comment: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "comment", b"comment", "dest_port", b"dest_port", "dst_zone", b"dst_zone", "id", b"id", "protocol", b"protocol", "src_ip", b"src_ip", "src_zone", b"src_zone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FirewallRule: _TypeAlias = FirewallRule  # noqa: Y015

@_typing.final
class FirewallRuleIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FirewallRuleIdRequest: _TypeAlias = FirewallRuleIdRequest  # noqa: Y015

@_typing.final
class FirewallRulesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RULES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___FirewallRule]: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        rules: _abc.Iterable[Global___FirewallRule] | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "rules", b"rules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FirewallRulesResponse: _TypeAlias = FirewallRulesResponse  # noqa: Y015
