"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ModelBackend:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ModelBackendEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ModelBackend.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MODEL_BACKEND_UNSPECIFIED: _ModelBackend.ValueType  # 0
    ONNX: _ModelBackend.ValueType  # 1
    TFLITE: _ModelBackend.ValueType  # 2

class ModelBackend(_ModelBackend, metaclass=_ModelBackendEnumTypeWrapper):
    """=====================
    Enums
    =====================
    """

MODEL_BACKEND_UNSPECIFIED: ModelBackend.ValueType  # 0
ONNX: ModelBackend.ValueType  # 1
TFLITE: ModelBackend.ValueType  # 2
Global___ModelBackend: _TypeAlias = ModelBackend  # noqa: Y015

class _ExecutionMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ExecutionModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ExecutionMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EXEC_CPU: _ExecutionMode.ValueType  # 0
    """Default: single/multi core CPU"""
    EXEC_GPU: _ExecutionMode.ValueType  # 1
    """GPU / NPU delegate"""
    EXEC_HIGH_THREADS: _ExecutionMode.ValueType  # 2
    """CPU with maximum thread count"""

class ExecutionMode(_ExecutionMode, metaclass=_ExecutionModeEnumTypeWrapper):
    """ExecutionMode controls which compute path the backend uses."""

EXEC_CPU: ExecutionMode.ValueType  # 0
"""Default: single/multi core CPU"""
EXEC_GPU: ExecutionMode.ValueType  # 1
"""GPU / NPU delegate"""
EXEC_HIGH_THREADS: ExecutionMode.ValueType  # 2
"""CPU with maximum thread count"""
Global___ExecutionMode: _TypeAlias = ExecutionMode  # noqa: Y015

class _TensorDataType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TensorDataTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TensorDataType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TENSOR_FLOAT32: _TensorDataType.ValueType  # 0
    """4-byte little-endian IEEE 754, normalised [0, 1]"""
    TENSOR_UINT8: _TensorDataType.ValueType  # 1
    """1-byte unsigned integer [0, 255]"""
    TENSOR_INT32: _TensorDataType.ValueType  # 2
    """4-byte little-endian signed integer"""
    TENSOR_INT64: _TensorDataType.ValueType  # 3
    """8-byte little-endian signed integer"""

class TensorDataType(_TensorDataType, metaclass=_TensorDataTypeEnumTypeWrapper):
    """TensorDataType describes how raw bytes in InferRequest/InferResponse are encoded."""

TENSOR_FLOAT32: TensorDataType.ValueType  # 0
"""4-byte little-endian IEEE 754, normalised [0, 1]"""
TENSOR_UINT8: TensorDataType.ValueType  # 1
"""1-byte unsigned integer [0, 255]"""
TENSOR_INT32: TensorDataType.ValueType  # 2
"""4-byte little-endian signed integer"""
TENSOR_INT64: TensorDataType.ValueType  # 3
"""8-byte little-endian signed integer"""
Global___TensorDataType: _TypeAlias = TensorDataType  # noqa: Y015

@_typing.final
class LoadModelRequest(_message.Message):
    """=====================
    Model Management
    =====================
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    MODEL_ID_FIELD_NUMBER: _builtins.int
    MODEL_PATH_FIELD_NUMBER: _builtins.int
    BACKEND_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    EXECUTION_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    model_path: _builtins.str
    """Path in local filesystem (or mounted storage)"""
    backend: Global___ModelBackend.ValueType
    """Backend type: ONNX / TFLITE"""
    version: _builtins.str
    """Optional: versioning"""
    execution: Global___ExecutionMode.ValueType
    """Execution preference for inference (default = CPU)"""
    @_builtins.property
    def options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Optional generic config (deprecated in favour of execution field below)"""

    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        model_path: _builtins.str = ...,
        backend: Global___ModelBackend.ValueType = ...,
        version: _builtins.str = ...,
        options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        execution: Global___ExecutionMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backend", b"backend", "execution", b"execution", "model_id", b"model_id", "model_path", b"model_path", "options", b"options", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoadModelRequest: _TypeAlias = LoadModelRequest  # noqa: Y015

@_typing.final
class LoadModelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    INPUTS_FIELD_NUMBER: _builtins.int
    OUTPUTS_FIELD_NUMBER: _builtins.int
    SKIPPED_UPLOAD_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    success: _builtins.bool
    skipped_upload: _builtins.bool
    """True when the model was already loaded in the backend and the upload was
    skipped. The schema (inputs/outputs) is still populated in this case.
    """
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    @_builtins.property
    def inputs(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorInfo]:
        """Input and output tensor schema reported by the backend after loading.
        Clients should use these to know how to pack input_data in InferRequest.
        """

    @_builtins.property
    def outputs(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorInfo]: ...
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _types_pb2.ErrorInfo | None = ...,
        inputs: _abc.Iterable[Global___TensorInfo] | None = ...,
        outputs: _abc.Iterable[Global___TensorInfo] | None = ...,
        skipped_upload: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "inputs", b"inputs", "model_id", b"model_id", "outputs", b"outputs", "skipped_upload", b"skipped_upload", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoadModelResponse: _TypeAlias = LoadModelResponse  # noqa: Y015

@_typing.final
class UploadModelChunk(_message.Message):
    """UploadModelChunk is a single message in the UploadAndLoadModel stream.
    The first chunk must carry meta; all others carry raw file bytes.
    """

    DESCRIPTOR: _descriptor.Descriptor

    META_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    @_builtins.property
    def meta(self) -> Global___UploadModelMeta: ...
    def __init__(
        self,
        *,
        meta: Global___UploadModelMeta | None = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "meta", b"meta", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "meta", b"meta", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["meta", "data"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___UploadModelChunk: _TypeAlias = UploadModelChunk  # noqa: Y015

@_typing.final
class UploadModelMeta(_message.Message):
    """UploadModelMeta is sent as the first chunk of UploadAndLoadModel."""

    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    BACKEND_FIELD_NUMBER: _builtins.int
    EXECUTION_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    TOTAL_BYTES_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    backend: Global___ModelBackend.ValueType
    execution: Global___ExecutionMode.ValueType
    version: _builtins.str
    total_bytes: _builtins.int
    """Expected total byte size of the model file (informational; used for progress)."""
    filename: _builtins.str
    """Original filename (used to determine file extension, e.g. "yolo.tflite")."""
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        backend: Global___ModelBackend.ValueType = ...,
        execution: Global___ExecutionMode.ValueType = ...,
        version: _builtins.str = ...,
        total_bytes: _builtins.int = ...,
        filename: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backend", b"backend", "execution", b"execution", "filename", b"filename", "model_id", b"model_id", "total_bytes", b"total_bytes", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UploadModelMeta: _TypeAlias = UploadModelMeta  # noqa: Y015

@_typing.final
class UnloadModelRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_id", b"model_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnloadModelRequest: _TypeAlias = UnloadModelRequest  # noqa: Y015

@_typing.final
class UnloadModelResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnloadModelResponse: _TypeAlias = UnloadModelResponse  # noqa: Y015

@_typing.final
class ListModelsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListModelsRequest: _TypeAlias = ListModelsRequest  # noqa: Y015

@_typing.final
class ListModelsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODELS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def models(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModelInfo]: ...
    def __init__(
        self,
        *,
        models: _abc.Iterable[Global___ModelInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["models", b"models"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListModelsResponse: _TypeAlias = ListModelsResponse  # noqa: Y015

@_typing.final
class ModelInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    BACKEND_FIELD_NUMBER: _builtins.int
    LOADED_AT_UNIX_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    version: _builtins.str
    backend: Global___ModelBackend.ValueType
    loaded_at_unix: _builtins.int
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        version: _builtins.str = ...,
        backend: Global___ModelBackend.ValueType = ...,
        loaded_at_unix: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backend", b"backend", "loaded_at_unix", b"loaded_at_unix", "model_id", b"model_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModelInfo: _TypeAlias = ModelInfo  # noqa: Y015

@_typing.final
class IsModelLoadedRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_ID_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_id", b"model_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IsModelLoadedRequest: _TypeAlias = IsModelLoadedRequest  # noqa: Y015

@_typing.final
class IsModelLoadedResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOADED_FIELD_NUMBER: _builtins.int
    INPUTS_FIELD_NUMBER: _builtins.int
    OUTPUTS_FIELD_NUMBER: _builtins.int
    loaded: _builtins.bool
    """True if the model is currently loaded and ready for inference."""
    @_builtins.property
    def inputs(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorInfo]:
        """Tensor schema — populated when loaded=true so the caller can start
        inference immediately without an extra LoadModel call.
        """

    @_builtins.property
    def outputs(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorInfo]: ...
    def __init__(
        self,
        *,
        loaded: _builtins.bool = ...,
        inputs: _abc.Iterable[Global___TensorInfo] | None = ...,
        outputs: _abc.Iterable[Global___TensorInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["inputs", b"inputs", "loaded", b"loaded", "outputs", b"outputs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IsModelLoadedResponse: _TypeAlias = IsModelLoadedResponse  # noqa: Y015

@_typing.final
class InferRequest(_message.Message):
    """=====================
    Inference
    =====================
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NamedInputsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    MODEL_ID_FIELD_NUMBER: _builtins.int
    INPUT_DATA_FIELD_NUMBER: _builtins.int
    INPUT_SHAPE_FIELD_NUMBER: _builtins.int
    NAMED_INPUTS_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    INPUT_DTYPE_FIELD_NUMBER: _builtins.int
    model_id: _builtins.str
    input_data: _builtins.bytes
    """Raw tensor input bytes.
    Encoding is determined by input_dtype:
      FLOAT32 (default) — little-endian IEEE 754 floats, normalised [0, 1]
      UINT8             — raw byte values [0, 255]
    """
    input_dtype: Global___TensorDataType.ValueType
    """Dtype of input_data / named_inputs bytes.
    Defaults to FLOAT32 if omitted; must match what the model expects.
    Use LoadModelResponse.inputs[0].dtype to determine the correct value.
    """
    @_builtins.property
    def input_shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Shape of the input tensor, e.g. [1, 640, 640, 3].
        If omitted, the shape reported by LoadModel (TensorInfo) is used.
        """

    @_builtins.property
    def named_inputs(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Optional: named inputs for multi-input models (map[tensor_name] -> raw bytes).
        Each value is encoded according to input_dtype.
        """

    @_builtins.property
    def params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Optional runtime parameters (pass-through to backend)"""

    def __init__(
        self,
        *,
        model_id: _builtins.str = ...,
        input_data: _builtins.bytes = ...,
        input_shape: _abc.Iterable[_builtins.int] | None = ...,
        named_inputs: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
        params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        input_dtype: Global___TensorDataType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input_data", b"input_data", "input_dtype", b"input_dtype", "input_shape", b"input_shape", "model_id", b"model_id", "named_inputs", b"named_inputs", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InferRequest: _TypeAlias = InferRequest  # noqa: Y015

@_typing.final
class InferResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NamedOutputsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    OUTPUT_DATA_FIELD_NUMBER: _builtins.int
    OUTPUT_SHAPE_FIELD_NUMBER: _builtins.int
    NAMED_OUTPUTS_FIELD_NUMBER: _builtins.int
    LATENCY_US_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    output_data: _builtins.bytes
    """First output tensor as raw bytes (little-endian float32 or uint8)"""
    latency_us: _builtins.int
    """Inference wall time measured at the backend"""
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    @_builtins.property
    def output_shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Shape of output_data"""

    @_builtins.property
    def named_outputs(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """All outputs by tensor name (same encoding as output_data)"""

    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _types_pb2.ErrorInfo | None = ...,
        output_data: _builtins.bytes = ...,
        output_shape: _abc.Iterable[_builtins.int] | None = ...,
        named_outputs: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
        latency_us: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "latency_us", b"latency_us", "named_outputs", b"named_outputs", "output_data", b"output_data", "output_shape", b"output_shape", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InferResponse: _TypeAlias = InferResponse  # noqa: Y015

@_typing.final
class TensorInfo(_message.Message):
    """=====================
    Shared tensor types
    =====================

    TensorInfo describes a single input or output tensor of a loaded model.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DTYPE_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    dtype: Global___TensorDataType.ValueType
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        dtype: Global___TensorDataType.ValueType = ...,
        shape: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dtype", b"dtype", "name", b"name", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TensorInfo: _TypeAlias = TensorInfo  # noqa: Y015
