"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _LogLevel:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LogLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOG_LEVEL_DEBUG: _LogLevel.ValueType  # 0
    LOG_LEVEL_INFO: _LogLevel.ValueType  # 1
    LOG_LEVEL_WARNING: _LogLevel.ValueType  # 2
    LOG_LEVEL_ERROR: _LogLevel.ValueType  # 3
    LOG_LEVEL_FATAL: _LogLevel.ValueType  # 4

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper):
    """─── Enums ───────────────────────────────────────────────────────────────────"""

LOG_LEVEL_DEBUG: LogLevel.ValueType  # 0
LOG_LEVEL_INFO: LogLevel.ValueType  # 1
LOG_LEVEL_WARNING: LogLevel.ValueType  # 2
LOG_LEVEL_ERROR: LogLevel.ValueType  # 3
LOG_LEVEL_FATAL: LogLevel.ValueType  # 4
Global___LogLevel: _TypeAlias = LogLevel  # noqa: Y015

@_typing.final
class LogSubscribeRequest(_message.Message):
    """─── Messages ────────────────────────────────────────────────────────────────

    Log subscription filter
    """

    DESCRIPTOR: _descriptor.Descriptor

    APP_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    app: _builtins.str
    """App name (empty = all apps)"""
    tag: _builtins.str
    """Tag filter (empty = all tags)"""
    level: Global___LogLevel.ValueType
    """Minimum log level to receive"""
    def __init__(
        self,
        *,
        app: _builtins.str = ...,
        tag: _builtins.str = ...,
        level: Global___LogLevel.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "level", b"level", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LogSubscribeRequest: _TypeAlias = LogSubscribeRequest  # noqa: Y015

@_typing.final
class LogEntry(_message.Message):
    """A single log entry"""

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    APP_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    timestamp_ms: _builtins.int
    """Unix timestamp in milliseconds"""
    app: _builtins.str
    """App that emitted the log"""
    tag: _builtins.str
    """Log tag"""
    level: Global___LogLevel.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        timestamp_ms: _builtins.int = ...,
        app: _builtins.str = ...,
        tag: _builtins.str = ...,
        level: Global___LogLevel.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "level", b"level", "message", b"message", "tag", b"tag", "timestamp_ms", b"timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LogEntry: _TypeAlias = LogEntry  # noqa: Y015
