# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.camera_service.v26 import camera_service_pb2 as api_dot_camera__service_dot_v26_dot_camera__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/camera_service/v26/camera_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureImage = channel.unary_unary(
                '/api.gravity.v26.CameraService/CaptureImage',
                request_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.CaptureImageRequest.SerializeToString,
                response_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.CaptureImageResponse.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/api.gravity.v26.CameraService/StreamFrames',
                request_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.StreamFramesRequest.SerializeToString,
                response_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.Frame.FromString,
                _registered_method=True)
        self.LockCamera = channel.unary_unary(
                '/api.gravity.v26.CameraService/LockCamera',
                request_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.LockRequest.SerializeToString,
                response_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.LockResponse.FromString,
                _registered_method=True)
        self.UnlockCamera = channel.unary_unary(
                '/api.gravity.v26.CameraService/UnlockCamera',
                request_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.UnlockRequest.SerializeToString,
                response_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.UnlockResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/api.gravity.v26.CameraService/GetDeviceInfo',
                request_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.DeviceInfoRequest.SerializeToString,
                response_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.DeviceInfoResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/api.gravity.v26.CameraService/ListDevices',
                request_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.ListDevicesResponse.FromString,
                _registered_method=True)


class CameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CaptureImage(self, request, context):
        """📸 Captura uma única imagem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """🎥 Stream contínuo (FPS camera)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockCamera(self, request, context):
        """🔒 Lock da câmara (evita acesso concorrente)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockCamera(self, request, context):
        """🔓 Libertar câmara
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """ℹ️ Informação do device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """📋 Lista todos os dispositivos V4L2 disponíveis no sistema
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureImage,
                    request_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.CaptureImageRequest.FromString,
                    response_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.CaptureImageResponse.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.StreamFramesRequest.FromString,
                    response_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.Frame.SerializeToString,
            ),
            'LockCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.LockCamera,
                    request_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.LockRequest.FromString,
                    response_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.LockResponse.SerializeToString,
            ),
            'UnlockCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockCamera,
                    request_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.UnlockRequest.FromString,
                    response_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.UnlockResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.DeviceInfoRequest.FromString,
                    response_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.DeviceInfoResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.ListDevicesRequest.FromString,
                    response_serializer=api_dot_camera__service_dot_v26_dot_camera__service__pb2.ListDevicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CaptureImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.CameraService/CaptureImage',
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.CaptureImageRequest.SerializeToString,
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.CaptureImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.CameraService/StreamFrames',
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.StreamFramesRequest.SerializeToString,
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.CameraService/LockCamera',
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.LockRequest.SerializeToString,
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.LockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.CameraService/UnlockCamera',
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.UnlockRequest.SerializeToString,
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.UnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.CameraService/GetDeviceInfo',
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.DeviceInfoRequest.SerializeToString,
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.DeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.CameraService/ListDevices',
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.ListDevicesRequest.SerializeToString,
            api_dot_camera__service_dot_v26_dot_camera__service__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
