"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CaptureImageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    """ex: "/dev/video0" """
    width: _builtins.int
    height: _builtins.int
    format: _builtins.str
    """"mjpeg", "yuyv" """
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        format: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "format", b"format", "height", b"height", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CaptureImageRequest: _TypeAlias = CaptureImageRequest  # noqa: Y015

@_typing.final
class CaptureImageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    image_data: _builtins.bytes
    """JPEG final"""
    format: _builtins.str
    timestamp: _builtins.int
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        image_data: _builtins.bytes = ...,
        format: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "format", b"format", "image_data", b"image_data", "success", b"success", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CaptureImageResponse: _TypeAlias = CaptureImageResponse  # noqa: Y015

@_typing.final
class StreamFramesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    FPS_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    fps: _builtins.int
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        fps: _builtins.int = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "fps", b"fps", "height", b"height", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamFramesRequest: _TypeAlias = StreamFramesRequest  # noqa: Y015

@_typing.final
class Frame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    timestamp: _builtins.int
    width: _builtins.int
    height: _builtins.int
    format: _builtins.str
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        timestamp: _builtins.int = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        format: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "format", b"format", "height", b"height", "timestamp", b"timestamp", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Frame: _TypeAlias = Frame  # noqa: Y015

@_typing.final
class LockRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    client_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        client_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "device_id", b"device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LockRequest: _TypeAlias = LockRequest  # noqa: Y015

@_typing.final
class LockResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LockResponse: _TypeAlias = LockResponse  # noqa: Y015

@_typing.final
class UnlockRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    client_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        client_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "device_id", b"device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnlockRequest: _TypeAlias = UnlockRequest  # noqa: Y015

@_typing.final
class UnlockResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnlockResponse: _TypeAlias = UnlockResponse  # noqa: Y015

@_typing.final
class DeviceInfoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceInfoRequest: _TypeAlias = DeviceInfoRequest  # noqa: Y015

@_typing.final
class DeviceInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    DRIVER_FIELD_NUMBER: _builtins.int
    CARD_FIELD_NUMBER: _builtins.int
    SUPPORTED_FORMATS_FIELD_NUMBER: _builtins.int
    RESOLUTIONS_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    driver: _builtins.str
    card: _builtins.str
    @_builtins.property
    def supported_formats(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def resolutions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        driver: _builtins.str = ...,
        card: _builtins.str = ...,
        supported_formats: _abc.Iterable[_builtins.str] | None = ...,
        resolutions: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["card", b"card", "device_id", b"device_id", "driver", b"driver", "resolutions", b"resolutions", "supported_formats", b"supported_formats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceInfoResponse: _TypeAlias = DeviceInfoResponse  # noqa: Y015

@_typing.final
class ListDevicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListDevicesRequest: _TypeAlias = ListDevicesRequest  # noqa: Y015

@_typing.final
class ListDevicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___DeviceInfoResponse]: ...
    def __init__(
        self,
        *,
        devices: _abc.Iterable[Global___DeviceInfoResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListDevicesResponse: _TypeAlias = ListDevicesResponse  # noqa: Y015
