"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.app_hub_service.v26 import app_hub_service_pb2 as _app_hub_service_pb2
from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AppHubServiceStub:
    """─── Service ──────────────────────────────────────────────────────────────────

    AppHubService is the gRPC registry that apps use to announce their WebUI.
    The HTTP portal (port 80) reads from this registry to populate the dashboard
    and to route proxy requests to the correct backend port.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AppHubServiceAsyncStub: ...
    RegisterService: _grpc.UnaryUnaryMultiCallable[_app_hub_service_pb2.RegisterServiceRequest, _app_hub_service_pb2.RegisterServiceResponse]
    """Registry — server identifies the caller from launch context (no service_id needed)"""
    UnregisterService: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    GetService: _grpc.UnaryUnaryMultiCallable[_app_hub_service_pb2.ServiceIdRequest, _app_hub_service_pb2.ServiceResponse]
    """Discovery"""
    ListServices: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _app_hub_service_pb2.ServicesResponse]
    AddRoute: _grpc.UnaryUnaryMultiCallable[_app_hub_service_pb2.AddRouteRequest, _types_pb2.BooleanResponse]
    """Routing"""
    RemoveRoute: _grpc.UnaryUnaryMultiCallable[_app_hub_service_pb2.RemoveRouteRequest, _types_pb2.BooleanResponse]
    GetRoutingTable: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _app_hub_service_pb2.RoutingTableResponse]
    WatchServices: _grpc.UnaryStreamMultiCallable[_types_pb2.Empty, _app_hub_service_pb2.ServiceEvent]
    """Events"""

@_typing.type_check_only
class AppHubServiceAsyncStub(AppHubServiceStub):
    """─── Service ──────────────────────────────────────────────────────────────────

    AppHubService is the gRPC registry that apps use to announce their WebUI.
    The HTTP portal (port 80) reads from this registry to populate the dashboard
    and to route proxy requests to the correct backend port.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    RegisterService: _aio.UnaryUnaryMultiCallable[_app_hub_service_pb2.RegisterServiceRequest, _app_hub_service_pb2.RegisterServiceResponse]  # type: ignore[assignment]
    """Registry — server identifies the caller from launch context (no service_id needed)"""
    UnregisterService: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetService: _aio.UnaryUnaryMultiCallable[_app_hub_service_pb2.ServiceIdRequest, _app_hub_service_pb2.ServiceResponse]  # type: ignore[assignment]
    """Discovery"""
    ListServices: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _app_hub_service_pb2.ServicesResponse]  # type: ignore[assignment]
    AddRoute: _aio.UnaryUnaryMultiCallable[_app_hub_service_pb2.AddRouteRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Routing"""
    RemoveRoute: _aio.UnaryUnaryMultiCallable[_app_hub_service_pb2.RemoveRouteRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetRoutingTable: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _app_hub_service_pb2.RoutingTableResponse]  # type: ignore[assignment]
    WatchServices: _aio.UnaryStreamMultiCallable[_types_pb2.Empty, _app_hub_service_pb2.ServiceEvent]  # type: ignore[assignment]
    """Events"""

class AppHubServiceServicer(metaclass=_abc_1.ABCMeta):
    """─── Service ──────────────────────────────────────────────────────────────────

    AppHubService is the gRPC registry that apps use to announce their WebUI.
    The HTTP portal (port 80) reads from this registry to populate the dashboard
    and to route proxy requests to the correct backend port.
    """

    @_abc_1.abstractmethod
    def RegisterService(
        self,
        request: _app_hub_service_pb2.RegisterServiceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_app_hub_service_pb2.RegisterServiceResponse, _abc.Awaitable[_app_hub_service_pb2.RegisterServiceResponse]]:
        """Registry — server identifies the caller from launch context (no service_id needed)"""

    @_abc_1.abstractmethod
    def UnregisterService(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetService(
        self,
        request: _app_hub_service_pb2.ServiceIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_app_hub_service_pb2.ServiceResponse, _abc.Awaitable[_app_hub_service_pb2.ServiceResponse]]:
        """Discovery"""

    @_abc_1.abstractmethod
    def ListServices(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_app_hub_service_pb2.ServicesResponse, _abc.Awaitable[_app_hub_service_pb2.ServicesResponse]]: ...

    @_abc_1.abstractmethod
    def AddRoute(
        self,
        request: _app_hub_service_pb2.AddRouteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Routing"""

    @_abc_1.abstractmethod
    def RemoveRoute(
        self,
        request: _app_hub_service_pb2.RemoveRouteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetRoutingTable(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_app_hub_service_pb2.RoutingTableResponse, _abc.Awaitable[_app_hub_service_pb2.RoutingTableResponse]]: ...

    @_abc_1.abstractmethod
    def WatchServices(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_app_hub_service_pb2.ServiceEvent], _abc.AsyncIterator[_app_hub_service_pb2.ServiceEvent]]:
        """Events"""

def add_AppHubServiceServicer_to_server(servicer: AppHubServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
