"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _HealthCheckType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HealthCheckTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_HealthCheckType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HEALTH_CHECK_UNKNOWN: _HealthCheckType.ValueType  # 0
    HEALTH_CHECK_HTTP: _HealthCheckType.ValueType  # 1
    """GET endpoint returns 2xx"""
    HEALTH_CHECK_TCP: _HealthCheckType.ValueType  # 2
    """TCP connect succeeds"""

class HealthCheckType(_HealthCheckType, metaclass=_HealthCheckTypeEnumTypeWrapper):
    """─── Enums ───────────────────────────────────────────────────────────────────"""

HEALTH_CHECK_UNKNOWN: HealthCheckType.ValueType  # 0
HEALTH_CHECK_HTTP: HealthCheckType.ValueType  # 1
"""GET endpoint returns 2xx"""
HEALTH_CHECK_TCP: HealthCheckType.ValueType  # 2
"""TCP connect succeeds"""
Global___HealthCheckType: _TypeAlias = HealthCheckType  # noqa: Y015

class _ServiceEventType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ServiceEventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ServiceEventType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SERVICE_EVENT_UNKNOWN: _ServiceEventType.ValueType  # 0
    SERVICE_EVENT_REGISTERED: _ServiceEventType.ValueType  # 1
    SERVICE_EVENT_UNREGISTERED: _ServiceEventType.ValueType  # 2
    SERVICE_EVENT_ROUTE_UPDATED: _ServiceEventType.ValueType  # 3
    SERVICE_EVENT_HEALTH_CHANGED: _ServiceEventType.ValueType  # 4

class ServiceEventType(_ServiceEventType, metaclass=_ServiceEventTypeEnumTypeWrapper): ...

SERVICE_EVENT_UNKNOWN: ServiceEventType.ValueType  # 0
SERVICE_EVENT_REGISTERED: ServiceEventType.ValueType  # 1
SERVICE_EVENT_UNREGISTERED: ServiceEventType.ValueType  # 2
SERVICE_EVENT_ROUTE_UPDATED: ServiceEventType.ValueType  # 3
SERVICE_EVENT_HEALTH_CHANGED: ServiceEventType.ValueType  # 4
Global___ServiceEventType: _TypeAlias = ServiceEventType  # noqa: Y015

class _ExposureMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ExposureModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ExposureMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EXPOSURE_MODE_PROXY: _ExposureMode.ValueType  # 0
    """default: portal reverse-proxies at ip/<route_path>"""
    EXPOSURE_MODE_REDIRECT: _ExposureMode.ValueType  # 1
    """portal redirects the browser to ip:<port>/ directly"""

class ExposureMode(_ExposureMode, metaclass=_ExposureModeEnumTypeWrapper):
    """Controls how the portal exposes the service to the browser."""

EXPOSURE_MODE_PROXY: ExposureMode.ValueType  # 0
"""default: portal reverse-proxies at ip/<route_path>"""
EXPOSURE_MODE_REDIRECT: ExposureMode.ValueType  # 1
"""portal redirects the browser to ip:<port>/ directly"""
Global___ExposureMode: _TypeAlias = ExposureMode  # noqa: Y015

@_typing.final
class Service(_message.Message):
    """─── Model Messages ───────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    PACKAGE_ID_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    HEALTHY_FIELD_NUMBER: _builtins.int
    ROUTES_FIELD_NUMBER: _builtins.int
    HEALTH_FIELD_NUMBER: _builtins.int
    EXPOSURE_MODE_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    """server-assigned UID — empty on registration, populated by server"""
    name: _builtins.str
    """display name shown in portal dashboard"""
    package_id: _builtins.str
    """installed app package_id — links service to the app tile"""
    host: _builtins.str
    port: _builtins.int
    healthy: _builtins.bool
    """last known health check result (populated by server)"""
    exposure_mode: Global___ExposureMode.ValueType
    """how the portal exposes this service (default: proxy)"""
    @_builtins.property
    def routes(self) -> _containers.RepeatedCompositeFieldContainer[Global___Route]: ...
    @_builtins.property
    def health(self) -> Global___HealthCheck: ...
    def __init__(
        self,
        *,
        service_id: _builtins.str = ...,
        name: _builtins.str = ...,
        package_id: _builtins.str = ...,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        healthy: _builtins.bool = ...,
        routes: _abc.Iterable[Global___Route] | None = ...,
        health: Global___HealthCheck | None = ...,
        exposure_mode: Global___ExposureMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["health", b"health"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exposure_mode", b"exposure_mode", "health", b"health", "healthy", b"healthy", "host", b"host", "name", b"name", "package_id", b"package_id", "port", b"port", "routes", b"routes", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Service: _TypeAlias = Service  # noqa: Y015

@_typing.final
class Route(_message.Message):
    """Route maps a URL path prefix to this service."""

    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """e.g. "/camera", "/nodered" """
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Route: _TypeAlias = Route  # noqa: Y015

@_typing.final
class HealthCheck(_message.Message):
    """HealthCheck describes how the portal probes service liveness."""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    ENDPOINT_FIELD_NUMBER: _builtins.int
    type: Global___HealthCheckType.ValueType
    endpoint: _builtins.str
    """HTTP only — path to probe, e.g. "/health" (empty = "/")"""
    def __init__(
        self,
        *,
        type: Global___HealthCheckType.ValueType = ...,
        endpoint: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["endpoint", b"endpoint", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthCheck: _TypeAlias = HealthCheck  # noqa: Y015

@_typing.final
class RoutingEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    service_id: _builtins.str
    target: _builtins.str
    """resolved "host:port" """
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        service_id: _builtins.str = ...,
        target: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path", "service_id", b"service_id", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RoutingEntry: _TypeAlias = RoutingEntry  # noqa: Y015

@_typing.final
class ServiceIdRequest(_message.Message):
    """─── Request Messages ─────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    def __init__(
        self,
        *,
        service_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServiceIdRequest: _TypeAlias = ServiceIdRequest  # noqa: Y015

@_typing.final
class RegisterServiceRequest(_message.Message):
    """RegisterServiceRequest contains only what the app needs to declare.
    name, package_id, and service_id are derived server-side from the caller's UID.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    ROUTES_FIELD_NUMBER: _builtins.int
    HEALTH_FIELD_NUMBER: _builtins.int
    EXPOSURE_MODE_FIELD_NUMBER: _builtins.int
    host: _builtins.str
    port: _builtins.int
    exposure_mode: Global___ExposureMode.ValueType
    @_builtins.property
    def routes(self) -> _containers.RepeatedCompositeFieldContainer[Global___Route]: ...
    @_builtins.property
    def health(self) -> Global___HealthCheck: ...
    def __init__(
        self,
        *,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        routes: _abc.Iterable[Global___Route] | None = ...,
        health: Global___HealthCheck | None = ...,
        exposure_mode: Global___ExposureMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["health", b"health"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exposure_mode", b"exposure_mode", "health", b"health", "host", b"host", "port", b"port", "routes", b"routes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterServiceRequest: _TypeAlias = RegisterServiceRequest  # noqa: Y015

@_typing.final
class AddRouteRequest(_message.Message):
    """AddRouteRequest — no service_id needed, server resolves ownership from caller identity."""

    DESCRIPTOR: _descriptor.Descriptor

    ROUTE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def route(self) -> Global___Route: ...
    def __init__(
        self,
        *,
        route: Global___Route | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["route", b"route"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["route", b"route"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddRouteRequest: _TypeAlias = AddRouteRequest  # noqa: Y015

@_typing.final
class RemoveRouteRequest(_message.Message):
    """RemoveRouteRequest — no service_id needed, server resolves ownership from caller identity."""

    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    def __init__(
        self,
        *,
        path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveRouteRequest: _TypeAlias = RemoveRouteRequest  # noqa: Y015

@_typing.final
class RegisterServiceResponse(_message.Message):
    """─── Response Messages ────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterServiceResponse: _TypeAlias = RegisterServiceResponse  # noqa: Y015

@_typing.final
class ServiceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def service(self) -> Global___Service: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        service: Global___Service | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServiceResponse: _TypeAlias = ServiceResponse  # noqa: Y015

@_typing.final
class ServicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def services(self) -> _containers.RepeatedCompositeFieldContainer[Global___Service]: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        services: _abc.Iterable[Global___Service] | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "services", b"services"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServicesResponse: _TypeAlias = ServicesResponse  # noqa: Y015

@_typing.final
class RoutingTableResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___RoutingEntry]: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___RoutingEntry] | None = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RoutingTableResponse: _TypeAlias = RoutingTableResponse  # noqa: Y015

@_typing.final
class ServiceEvent(_message.Message):
    """─── Events ───────────────────────────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    SERVICE_FIELD_NUMBER: _builtins.int
    type: Global___ServiceEventType.ValueType
    @_builtins.property
    def service(self) -> Global___Service: ...
    def __init__(
        self,
        *,
        type: Global___ServiceEventType.ValueType = ...,
        service: Global___Service | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["service", b"service", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServiceEvent: _TypeAlias = ServiceEvent  # noqa: Y015
