# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.app_hub_service.v26 import app_hub_service_pb2 as api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2
from api.common import types_pb2 as api_dot_common_dot_types__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/app_hub_service/v26/app_hub_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppHubServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    AppHubService is the gRPC registry that apps use to announce their WebUI.
    The HTTP portal (port 80) reads from this registry to populate the dashboard
    and to route proxy requests to the correct backend port.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterService = channel.unary_unary(
                '/api.gravity.v26.AppHubService/RegisterService',
                request_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RegisterServiceRequest.SerializeToString,
                response_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RegisterServiceResponse.FromString,
                _registered_method=True)
        self.UnregisterService = channel.unary_unary(
                '/api.gravity.v26.AppHubService/UnregisterService',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetService = channel.unary_unary(
                '/api.gravity.v26.AppHubService/GetService',
                request_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceIdRequest.SerializeToString,
                response_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceResponse.FromString,
                _registered_method=True)
        self.ListServices = channel.unary_unary(
                '/api.gravity.v26.AppHubService/ListServices',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServicesResponse.FromString,
                _registered_method=True)
        self.AddRoute = channel.unary_unary(
                '/api.gravity.v26.AppHubService/AddRoute',
                request_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.AddRouteRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.RemoveRoute = channel.unary_unary(
                '/api.gravity.v26.AppHubService/RemoveRoute',
                request_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RemoveRouteRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetRoutingTable = channel.unary_unary(
                '/api.gravity.v26.AppHubService/GetRoutingTable',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RoutingTableResponse.FromString,
                _registered_method=True)
        self.WatchServices = channel.unary_stream(
                '/api.gravity.v26.AppHubService/WatchServices',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceEvent.FromString,
                _registered_method=True)


class AppHubServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    AppHubService is the gRPC registry that apps use to announce their WebUI.
    The HTTP portal (port 80) reads from this registry to populate the dashboard
    and to route proxy requests to the correct backend port.
    """

    def RegisterService(self, request, context):
        """Registry — server identifies the caller from launch context (no service_id needed)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetService(self, request, context):
        """Discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRoute(self, request, context):
        """Routing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutingTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchServices(self, request, context):
        """Events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppHubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RegisterServiceRequest.FromString,
                    response_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RegisterServiceResponse.SerializeToString,
            ),
            'UnregisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterService,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetService,
                    request_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceIdRequest.FromString,
                    response_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceResponse.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServicesResponse.SerializeToString,
            ),
            'AddRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoute,
                    request_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.AddRouteRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'RemoveRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRoute,
                    request_deserializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RemoveRouteRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetRoutingTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingTable,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RoutingTableResponse.SerializeToString,
            ),
            'WatchServices': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchServices,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.AppHubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.AppHubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppHubService(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    AppHubService is the gRPC registry that apps use to announce their WebUI.
    The HTTP portal (port 80) reads from this registry to populate the dashboard
    and to route proxy requests to the correct backend port.
    """

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/RegisterService',
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RegisterServiceRequest.SerializeToString,
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RegisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/UnregisterService',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/GetService',
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceIdRequest.SerializeToString,
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/ListServices',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/AddRoute',
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.AddRouteRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/RemoveRoute',
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RemoveRouteRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.AppHubService/GetRoutingTable',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.RoutingTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.AppHubService/WatchServices',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_app__hub__service_dot_v26_dot_app__hub__service__pb2.ServiceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
