"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from api.gpio_service.v26 import gpio_service_pb2 as _gpio_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GpioServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GpioServiceAsyncStub: ...
    ListGPIOPins: _grpc.UnaryUnaryMultiCallable[_types_pb2.Void, _gpio_service_pb2.ListGpioPinsResponse]
    """GPIO"""
    GetGPIOLevel: _grpc.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioLevelRequest, _gpio_service_pb2.GpioLevelResponse]
    SetGPIOLevel: _grpc.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioLevelRequest, _gpio_service_pb2.GpioLevelResponse]
    GetGPIODirection: _grpc.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioDirectionRequest, _gpio_service_pb2.GpioDirectionResponse]
    SetGPIODirection: _grpc.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioDirectionRequest, _gpio_service_pb2.GpioDirectionResponse]

@_typing.type_check_only
class GpioServiceAsyncStub(GpioServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    ListGPIOPins: _aio.UnaryUnaryMultiCallable[_types_pb2.Void, _gpio_service_pb2.ListGpioPinsResponse]  # type: ignore[assignment]
    """GPIO"""
    GetGPIOLevel: _aio.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioLevelRequest, _gpio_service_pb2.GpioLevelResponse]  # type: ignore[assignment]
    SetGPIOLevel: _aio.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioLevelRequest, _gpio_service_pb2.GpioLevelResponse]  # type: ignore[assignment]
    GetGPIODirection: _aio.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioDirectionRequest, _gpio_service_pb2.GpioDirectionResponse]  # type: ignore[assignment]
    SetGPIODirection: _aio.UnaryUnaryMultiCallable[_gpio_service_pb2.GpioDirectionRequest, _gpio_service_pb2.GpioDirectionResponse]  # type: ignore[assignment]

class GpioServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def ListGPIOPins(
        self,
        request: _types_pb2.Void,
        context: _ServicerContext,
    ) -> _typing.Union[_gpio_service_pb2.ListGpioPinsResponse, _abc.Awaitable[_gpio_service_pb2.ListGpioPinsResponse]]:
        """GPIO"""

    @_abc_1.abstractmethod
    def GetGPIOLevel(
        self,
        request: _gpio_service_pb2.GpioLevelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_gpio_service_pb2.GpioLevelResponse, _abc.Awaitable[_gpio_service_pb2.GpioLevelResponse]]: ...

    @_abc_1.abstractmethod
    def SetGPIOLevel(
        self,
        request: _gpio_service_pb2.GpioLevelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_gpio_service_pb2.GpioLevelResponse, _abc.Awaitable[_gpio_service_pb2.GpioLevelResponse]]: ...

    @_abc_1.abstractmethod
    def GetGPIODirection(
        self,
        request: _gpio_service_pb2.GpioDirectionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_gpio_service_pb2.GpioDirectionResponse, _abc.Awaitable[_gpio_service_pb2.GpioDirectionResponse]]: ...

    @_abc_1.abstractmethod
    def SetGPIODirection(
        self,
        request: _gpio_service_pb2.GpioDirectionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_gpio_service_pb2.GpioDirectionResponse, _abc.Awaitable[_gpio_service_pb2.GpioDirectionResponse]]: ...

def add_GpioServiceServicer_to_server(servicer: GpioServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
