# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/gpio_service/v26/gpio_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/gpio_service/v26/gpio_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import types_pb2 as api_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'api/gpio_service/v26/gpio_service.proto\x12\x0f\x61pi.gravity.v26\x1a\x16\x61pi/common/types.proto\"7\n\x07GpioPin\x12\x10\n\x08gpiochip\x18\x01 \x01(\x05\x12\x0c\n\x04line\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"k\n\x14ListGpioPinsResponse\x12&\n\x04pins\x18\x01 \x03(\x0b\x32\x18.api.gravity.v26.GpioPin\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1c.api.gravity.types.ErrorInfo\"d\n\x10GpioLevelRequest\x12%\n\x03pin\x18\x01 \x01(\x0b\x32\x18.api.gravity.v26.GpioPin\x12)\n\x05level\x18\x02 \x01(\x0e\x32\x1a.api.gravity.v26.GpioLevel\"k\n\x11GpioLevelResponse\x12)\n\x05level\x18\x01 \x01(\x0e\x32\x1a.api.gravity.v26.GpioLevel\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1c.api.gravity.types.ErrorInfo\"p\n\x14GpioDirectionRequest\x12%\n\x03pin\x18\x01 \x01(\x0b\x32\x18.api.gravity.v26.GpioPin\x12\x31\n\tdirection\x18\x02 \x01(\x0e\x32\x1e.api.gravity.v26.GpioDirection\"w\n\x15GpioDirectionResponse\x12\x31\n\tdirection\x18\x01 \x01(\x0e\x32\x1e.api.gravity.v26.GpioDirection\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1c.api.gravity.types.ErrorInfo*4\n\tGpioLevel\x12\x12\n\x0eGPIO_LEVEL_LOW\x10\x00\x12\x13\n\x0fGPIO_LEVEL_HIGH\x10\x01*2\n\rGpioDirection\x12\x10\n\x0cGPIO_DIR_OUT\x10\x00\x12\x0f\n\x0bGPIO_DIR_IN\x10\x01\x32\xd1\x03\n\x0bGpioService\x12N\n\x0cListGPIOPins\x12\x17.api.gravity.types.Void\x1a%.api.gravity.v26.ListGpioPinsResponse\x12U\n\x0cGetGPIOLevel\x12!.api.gravity.v26.GpioLevelRequest\x1a\".api.gravity.v26.GpioLevelResponse\x12U\n\x0cSetGPIOLevel\x12!.api.gravity.v26.GpioLevelRequest\x1a\".api.gravity.v26.GpioLevelResponse\x12\x61\n\x10GetGPIODirection\x12%.api.gravity.v26.GpioDirectionRequest\x1a&.api.gravity.v26.GpioDirectionResponse\x12\x61\n\x10SetGPIODirection\x12%.api.gravity.v26.GpioDirectionRequest\x1a&.api.gravity.v26.GpioDirectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.gpio_service.v26.gpio_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPIOLEVEL']._serialized_start=696
  _globals['_GPIOLEVEL']._serialized_end=748
  _globals['_GPIODIRECTION']._serialized_start=750
  _globals['_GPIODIRECTION']._serialized_end=800
  _globals['_GPIOPIN']._serialized_start=84
  _globals['_GPIOPIN']._serialized_end=139
  _globals['_LISTGPIOPINSRESPONSE']._serialized_start=141
  _globals['_LISTGPIOPINSRESPONSE']._serialized_end=248
  _globals['_GPIOLEVELREQUEST']._serialized_start=250
  _globals['_GPIOLEVELREQUEST']._serialized_end=350
  _globals['_GPIOLEVELRESPONSE']._serialized_start=352
  _globals['_GPIOLEVELRESPONSE']._serialized_end=459
  _globals['_GPIODIRECTIONREQUEST']._serialized_start=461
  _globals['_GPIODIRECTIONREQUEST']._serialized_end=573
  _globals['_GPIODIRECTIONRESPONSE']._serialized_start=575
  _globals['_GPIODIRECTIONRESPONSE']._serialized_end=694
  _globals['_GPIOSERVICE']._serialized_start=803
  _globals['_GPIOSERVICE']._serialized_end=1268
# @@protoc_insertion_point(module_scope)
