# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.common import types_pb2 as api_dot_common_dot_types__pb2
from api.gpio_service.v26 import gpio_service_pb2 as api_dot_gpio__service_dot_v26_dot_gpio__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/gpio_service/v26/gpio_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GpioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListGPIOPins = channel.unary_unary(
                '/api.gravity.v26.GpioService/ListGPIOPins',
                request_serializer=api_dot_common_dot_types__pb2.Void.SerializeToString,
                response_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.ListGpioPinsResponse.FromString,
                _registered_method=True)
        self.GetGPIOLevel = channel.unary_unary(
                '/api.gravity.v26.GpioService/GetGPIOLevel',
                request_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelRequest.SerializeToString,
                response_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelResponse.FromString,
                _registered_method=True)
        self.SetGPIOLevel = channel.unary_unary(
                '/api.gravity.v26.GpioService/SetGPIOLevel',
                request_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelRequest.SerializeToString,
                response_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelResponse.FromString,
                _registered_method=True)
        self.GetGPIODirection = channel.unary_unary(
                '/api.gravity.v26.GpioService/GetGPIODirection',
                request_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionRequest.SerializeToString,
                response_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionResponse.FromString,
                _registered_method=True)
        self.SetGPIODirection = channel.unary_unary(
                '/api.gravity.v26.GpioService/SetGPIODirection',
                request_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionRequest.SerializeToString,
                response_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionResponse.FromString,
                _registered_method=True)


class GpioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListGPIOPins(self, request, context):
        """GPIO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGPIOLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGPIOLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGPIODirection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGPIODirection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GpioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListGPIOPins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGPIOPins,
                    request_deserializer=api_dot_common_dot_types__pb2.Void.FromString,
                    response_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.ListGpioPinsResponse.SerializeToString,
            ),
            'GetGPIOLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGPIOLevel,
                    request_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelRequest.FromString,
                    response_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelResponse.SerializeToString,
            ),
            'SetGPIOLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGPIOLevel,
                    request_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelRequest.FromString,
                    response_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelResponse.SerializeToString,
            ),
            'GetGPIODirection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGPIODirection,
                    request_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionRequest.FromString,
                    response_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionResponse.SerializeToString,
            ),
            'SetGPIODirection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGPIODirection,
                    request_deserializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionRequest.FromString,
                    response_serializer=api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.GpioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.GpioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GpioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListGPIOPins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.GpioService/ListGPIOPins',
            api_dot_common_dot_types__pb2.Void.SerializeToString,
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.ListGpioPinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGPIOLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.GpioService/GetGPIOLevel',
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelRequest.SerializeToString,
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGPIOLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.GpioService/SetGPIOLevel',
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelRequest.SerializeToString,
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGPIODirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.GpioService/GetGPIODirection',
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionRequest.SerializeToString,
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGPIODirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.GpioService/SetGPIODirection',
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionRequest.SerializeToString,
            api_dot_gpio__service_dot_v26_dot_gpio__service__pb2.GpioDirectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
