"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from api.time_service.v26 import time_service_pb2 as _time_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class TimeServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TimeServiceAsyncStub: ...
    GetNTPConfig: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.NTPConfigResponse]
    """NTP config — atomic, applies all settings in one reload"""
    SetNTPConfig: _grpc.UnaryUnaryMultiCallable[_time_service_pb2.NTPConfigRequest, _types_pb2.BooleanResponse]
    IsNTPSyncEnabled: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    """NTP Sync — convenience wrappers (internally call SetNTPConfig)"""
    EnableNTPSync: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    DisableNTPSync: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    GetTimeSeconds: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.GetTimeResponse]
    """Time"""
    SetTimeSeconds: _grpc.UnaryUnaryMultiCallable[_time_service_pb2.SetTimeRequest, _types_pb2.BooleanResponse]
    GetTimeMillis: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.GetTimeResponse]
    SetTimeMillis: _grpc.UnaryUnaryMultiCallable[_time_service_pb2.SetTimeRequest, _types_pb2.BooleanResponse]
    GetUptime: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.UptimeResponse]
    """Uptime"""

@_typing.type_check_only
class TimeServiceAsyncStub(TimeServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetNTPConfig: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.NTPConfigResponse]  # type: ignore[assignment]
    """NTP config — atomic, applies all settings in one reload"""
    SetNTPConfig: _aio.UnaryUnaryMultiCallable[_time_service_pb2.NTPConfigRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    IsNTPSyncEnabled: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """NTP Sync — convenience wrappers (internally call SetNTPConfig)"""
    EnableNTPSync: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    DisableNTPSync: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetTimeSeconds: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.GetTimeResponse]  # type: ignore[assignment]
    """Time"""
    SetTimeSeconds: _aio.UnaryUnaryMultiCallable[_time_service_pb2.SetTimeRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetTimeMillis: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.GetTimeResponse]  # type: ignore[assignment]
    SetTimeMillis: _aio.UnaryUnaryMultiCallable[_time_service_pb2.SetTimeRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetUptime: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _time_service_pb2.UptimeResponse]  # type: ignore[assignment]
    """Uptime"""

class TimeServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetNTPConfig(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_time_service_pb2.NTPConfigResponse, _abc.Awaitable[_time_service_pb2.NTPConfigResponse]]:
        """NTP config — atomic, applies all settings in one reload"""

    @_abc_1.abstractmethod
    def SetNTPConfig(
        self,
        request: _time_service_pb2.NTPConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def IsNTPSyncEnabled(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """NTP Sync — convenience wrappers (internally call SetNTPConfig)"""

    @_abc_1.abstractmethod
    def EnableNTPSync(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def DisableNTPSync(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetTimeSeconds(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_time_service_pb2.GetTimeResponse, _abc.Awaitable[_time_service_pb2.GetTimeResponse]]:
        """Time"""

    @_abc_1.abstractmethod
    def SetTimeSeconds(
        self,
        request: _time_service_pb2.SetTimeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetTimeMillis(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_time_service_pb2.GetTimeResponse, _abc.Awaitable[_time_service_pb2.GetTimeResponse]]: ...

    @_abc_1.abstractmethod
    def SetTimeMillis(
        self,
        request: _time_service_pb2.SetTimeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetUptime(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_time_service_pb2.UptimeResponse, _abc.Awaitable[_time_service_pb2.UptimeResponse]]:
        """Uptime"""

def add_TimeServiceServicer_to_server(servicer: TimeServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
