"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class NTPConfigRequest(_message.Message):
    """Atomic NTP configuration"""

    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    SERVERS_FIELD_NUMBER: _builtins.int
    RTC_SYNC_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    rtc_sync: _builtins.bool
    """Write NTP time to hardware clock"""
    @_builtins.property
    def servers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        servers: _abc.Iterable[_builtins.str] | None = ...,
        rtc_sync: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "rtc_sync", b"rtc_sync", "servers", b"servers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NTPConfigRequest: _TypeAlias = NTPConfigRequest  # noqa: Y015

@_typing.final
class NTPConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    SERVERS_FIELD_NUMBER: _builtins.int
    RTC_SYNC_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    rtc_sync: _builtins.bool
    @_builtins.property
    def servers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        servers: _abc.Iterable[_builtins.str] | None = ...,
        rtc_sync: _builtins.bool = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "error", b"error", "rtc_sync", b"rtc_sync", "servers", b"servers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NTPConfigResponse: _TypeAlias = NTPConfigResponse  # noqa: Y015

@_typing.final
class GetTimeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    time: _builtins.int
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        time: _builtins.int = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "time", b"time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTimeResponse: _TypeAlias = GetTimeResponse  # noqa: Y015

@_typing.final
class SetTimeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    time: _builtins.int
    def __init__(
        self,
        *,
        time: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["time", b"time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetTimeRequest: _TypeAlias = SetTimeRequest  # noqa: Y015

@_typing.final
class UptimeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UPTIME_SEC_FIELD_NUMBER: _builtins.int
    UPTIME_MILLIS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    uptime_sec: _builtins.int
    uptime_millis: _builtins.int
    @_builtins.property
    def error(self) -> _types_pb2.ErrorInfo: ...
    def __init__(
        self,
        *,
        uptime_sec: _builtins.int = ...,
        uptime_millis: _builtins.int = ...,
        error: _types_pb2.ErrorInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "uptime_millis", b"uptime_millis", "uptime_sec", b"uptime_sec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UptimeResponse: _TypeAlias = UptimeResponse  # noqa: Y015
