# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.common import types_pb2 as api_dot_common_dot_types__pb2
from api.time_service.v26 import time_service_pb2 as api_dot_time__service_dot_v26_dot_time__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/time_service/v26/time_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNTPConfig = channel.unary_unary(
                '/api.gravity.v26.TimeService/GetNTPConfig',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.NTPConfigResponse.FromString,
                _registered_method=True)
        self.SetNTPConfig = channel.unary_unary(
                '/api.gravity.v26.TimeService/SetNTPConfig',
                request_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.NTPConfigRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.IsNTPSyncEnabled = channel.unary_unary(
                '/api.gravity.v26.TimeService/IsNTPSyncEnabled',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.EnableNTPSync = channel.unary_unary(
                '/api.gravity.v26.TimeService/EnableNTPSync',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisableNTPSync = channel.unary_unary(
                '/api.gravity.v26.TimeService/DisableNTPSync',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetTimeSeconds = channel.unary_unary(
                '/api.gravity.v26.TimeService/GetTimeSeconds',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.GetTimeResponse.FromString,
                _registered_method=True)
        self.SetTimeSeconds = channel.unary_unary(
                '/api.gravity.v26.TimeService/SetTimeSeconds',
                request_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.SetTimeRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetTimeMillis = channel.unary_unary(
                '/api.gravity.v26.TimeService/GetTimeMillis',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.GetTimeResponse.FromString,
                _registered_method=True)
        self.SetTimeMillis = channel.unary_unary(
                '/api.gravity.v26.TimeService/SetTimeMillis',
                request_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.SetTimeRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetUptime = channel.unary_unary(
                '/api.gravity.v26.TimeService/GetUptime',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.UptimeResponse.FromString,
                _registered_method=True)


class TimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNTPConfig(self, request, context):
        """NTP config — atomic, applies all settings in one reload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNTPConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsNTPSyncEnabled(self, request, context):
        """NTP Sync — convenience wrappers (internally call SetNTPConfig)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableNTPSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableNTPSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeSeconds(self, request, context):
        """Time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeSeconds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeMillis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeMillis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUptime(self, request, context):
        """Uptime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNTPConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNTPConfig,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.NTPConfigResponse.SerializeToString,
            ),
            'SetNTPConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNTPConfig,
                    request_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.NTPConfigRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'IsNTPSyncEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsNTPSyncEnabled,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'EnableNTPSync': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableNTPSync,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisableNTPSync': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableNTPSync,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetTimeSeconds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeSeconds,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.GetTimeResponse.SerializeToString,
            ),
            'SetTimeSeconds': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeSeconds,
                    request_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.SetTimeRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetTimeMillis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeMillis,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.GetTimeResponse.SerializeToString,
            ),
            'SetTimeMillis': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeMillis,
                    request_deserializer=api_dot_time__service_dot_v26_dot_time__service__pb2.SetTimeRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetUptime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUptime,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_time__service_dot_v26_dot_time__service__pb2.UptimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.TimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.TimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNTPConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/GetNTPConfig',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_time__service_dot_v26_dot_time__service__pb2.NTPConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNTPConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/SetNTPConfig',
            api_dot_time__service_dot_v26_dot_time__service__pb2.NTPConfigRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsNTPSyncEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/IsNTPSyncEnabled',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableNTPSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/EnableNTPSync',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableNTPSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/DisableNTPSync',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeSeconds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/GetTimeSeconds',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_time__service_dot_v26_dot_time__service__pb2.GetTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTimeSeconds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/SetTimeSeconds',
            api_dot_time__service_dot_v26_dot_time__service__pb2.SetTimeRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeMillis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/GetTimeMillis',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_time__service_dot_v26_dot_time__service__pb2.GetTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTimeMillis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/SetTimeMillis',
            api_dot_time__service_dot_v26_dot_time__service__pb2.SetTimeRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUptime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.TimeService/GetUptime',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_time__service_dot_v26_dot_time__service__pb2.UptimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
