"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.common import types_pb2 as _types_pb2
from api.ethernet_service.v26 import ethernet_service_pb2 as _ethernet_service_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EthernetServiceStub:
    """EthernetService definition"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EthernetServiceAsyncStub: ...
    ListEthernetInterfaces: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _ethernet_service_pb2.EthernetInterfacesResponse]
    """Lists all Ethernet interfaces and their states"""
    IsEthernetConnected: _grpc.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _types_pb2.BooleanResponse]
    """Checks if an Ethernet interface is connected"""
    GetEthernetLinkProperties: _grpc.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _ethernet_service_pb2.EthernetLinkPropertiesResponse]
    """Returns link properties of an interface"""
    SetEthernetConfig: _grpc.UnaryUnaryMultiCallable[_ethernet_service_pb2.EthernetConfig, _types_pb2.BooleanResponse]
    """Configures static IP or DHCP for an interface"""
    EnableEthernet: _grpc.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _types_pb2.BooleanResponse]
    """Enables the Ethernet interface"""
    DisableEthernet: _grpc.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _types_pb2.BooleanResponse]
    """Disables the Ethernet interface"""

@_typing.type_check_only
class EthernetServiceAsyncStub(EthernetServiceStub):
    """EthernetService definition"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    ListEthernetInterfaces: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _ethernet_service_pb2.EthernetInterfacesResponse]  # type: ignore[assignment]
    """Lists all Ethernet interfaces and their states"""
    IsEthernetConnected: _aio.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Checks if an Ethernet interface is connected"""
    GetEthernetLinkProperties: _aio.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _ethernet_service_pb2.EthernetLinkPropertiesResponse]  # type: ignore[assignment]
    """Returns link properties of an interface"""
    SetEthernetConfig: _aio.UnaryUnaryMultiCallable[_ethernet_service_pb2.EthernetConfig, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Configures static IP or DHCP for an interface"""
    EnableEthernet: _aio.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Enables the Ethernet interface"""
    DisableEthernet: _aio.UnaryUnaryMultiCallable[_ethernet_service_pb2.InterfaceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Disables the Ethernet interface"""

class EthernetServiceServicer(metaclass=_abc_1.ABCMeta):
    """EthernetService definition"""

    @_abc_1.abstractmethod
    def ListEthernetInterfaces(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_ethernet_service_pb2.EthernetInterfacesResponse, _abc.Awaitable[_ethernet_service_pb2.EthernetInterfacesResponse]]:
        """Lists all Ethernet interfaces and their states"""

    @_abc_1.abstractmethod
    def IsEthernetConnected(
        self,
        request: _ethernet_service_pb2.InterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Checks if an Ethernet interface is connected"""

    @_abc_1.abstractmethod
    def GetEthernetLinkProperties(
        self,
        request: _ethernet_service_pb2.InterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_ethernet_service_pb2.EthernetLinkPropertiesResponse, _abc.Awaitable[_ethernet_service_pb2.EthernetLinkPropertiesResponse]]:
        """Returns link properties of an interface"""

    @_abc_1.abstractmethod
    def SetEthernetConfig(
        self,
        request: _ethernet_service_pb2.EthernetConfig,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Configures static IP or DHCP for an interface"""

    @_abc_1.abstractmethod
    def EnableEthernet(
        self,
        request: _ethernet_service_pb2.InterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Enables the Ethernet interface"""

    @_abc_1.abstractmethod
    def DisableEthernet(
        self,
        request: _ethernet_service_pb2.InterfaceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Disables the Ethernet interface"""

def add_EthernetServiceServicer_to_server(servicer: EthernetServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
