# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.common import types_pb2 as api_dot_common_dot_types__pb2
from api.ethernet_service.v26 import ethernet_service_pb2 as api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/ethernet_service/v26/ethernet_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EthernetServiceStub(object):
    """EthernetService definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEthernetInterfaces = channel.unary_unary(
                '/api.gravity.v26.EthernetService/ListEthernetInterfaces',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetInterfacesResponse.FromString,
                _registered_method=True)
        self.IsEthernetConnected = channel.unary_unary(
                '/api.gravity.v26.EthernetService/IsEthernetConnected',
                request_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetEthernetLinkProperties = channel.unary_unary(
                '/api.gravity.v26.EthernetService/GetEthernetLinkProperties',
                request_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetLinkPropertiesResponse.FromString,
                _registered_method=True)
        self.SetEthernetConfig = channel.unary_unary(
                '/api.gravity.v26.EthernetService/SetEthernetConfig',
                request_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetConfig.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.EnableEthernet = channel.unary_unary(
                '/api.gravity.v26.EthernetService/EnableEthernet',
                request_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisableEthernet = channel.unary_unary(
                '/api.gravity.v26.EthernetService/DisableEthernet',
                request_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)


class EthernetServiceServicer(object):
    """EthernetService definition
    """

    def ListEthernetInterfaces(self, request, context):
        """Lists all Ethernet interfaces and their states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsEthernetConnected(self, request, context):
        """Checks if an Ethernet interface is connected
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEthernetLinkProperties(self, request, context):
        """Returns link properties of an interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEthernetConfig(self, request, context):
        """Configures static IP or DHCP for an interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableEthernet(self, request, context):
        """Enables the Ethernet interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableEthernet(self, request, context):
        """Disables the Ethernet interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EthernetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEthernetInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEthernetInterfaces,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetInterfacesResponse.SerializeToString,
            ),
            'IsEthernetConnected': grpc.unary_unary_rpc_method_handler(
                    servicer.IsEthernetConnected,
                    request_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetEthernetLinkProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEthernetLinkProperties,
                    request_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.FromString,
                    response_serializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetLinkPropertiesResponse.SerializeToString,
            ),
            'SetEthernetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEthernetConfig,
                    request_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetConfig.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'EnableEthernet': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableEthernet,
                    request_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisableEthernet': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableEthernet,
                    request_deserializer=api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.EthernetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.EthernetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EthernetService(object):
    """EthernetService definition
    """

    @staticmethod
    def ListEthernetInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.EthernetService/ListEthernetInterfaces',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetInterfacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsEthernetConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.EthernetService/IsEthernetConnected',
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEthernetLinkProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.EthernetService/GetEthernetLinkProperties',
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetLinkPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEthernetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.EthernetService/SetEthernetConfig',
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.EthernetConfig.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableEthernet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.EthernetService/EnableEthernet',
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableEthernet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.EthernetService/DisableEthernet',
            api_dot_ethernet__service_dot_v26_dot_ethernet__service__pb2.InterfaceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
