# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.bluetooth_service.v26 import bluetooth_service_pb2 as api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2
from api.common import types_pb2 as api_dot_common_dot_types__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/bluetooth_service/v26/bluetooth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BluetoothServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAdapterInfo = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GetAdapterInfo',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BluetoothAdapterInfoResponse.FromString,
                _registered_method=True)
        self.EnableBluetooth = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/EnableBluetooth',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisableBluetooth = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/DisableBluetooth',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetLocalName = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GetLocalName',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.StringResponse.FromString,
                _registered_method=True)
        self.SetLocalName = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/SetLocalName',
                request_serializer=api_dot_common_dot_types__pb2.StringRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.SetDiscoverable = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/SetDiscoverable',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.SetDiscoverableRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.StartScan = channel.unary_stream(
                '/api.gravity.v26.BluetoothService/StartScan',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.ClassicScanResult.FromString,
                _registered_method=True)
        self.GetBondedDevices = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GetBondedDevices',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BondedDevicesResponse.FromString,
                _registered_method=True)
        self.BondDevice = channel.unary_stream(
                '/api.gravity.v26.BluetoothService/BondDevice',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BondEvent.FromString,
                _registered_method=True)
        self.RemoveBond = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/RemoveBond',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.ConnectDevice = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/ConnectDevice',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.DisconnectDevice = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/DisconnectDevice',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetConnectionState = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GetConnectionState',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtConnectionStateResponse.FromString,
                _registered_method=True)
        self.StartBleScan = channel.unary_stream(
                '/api.gravity.v26.BluetoothService/StartBleScan',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BleScanRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BleScanResult.FromString,
                _registered_method=True)
        self.GattConnect = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattConnect',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GattDisconnect = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattDisconnect',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetGattState = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GetGattState',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattStateResponse.FromString,
                _registered_method=True)
        self.GattDiscoverServices = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattDiscoverServices',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattServicesResponse.FromString,
                _registered_method=True)
        self.GattReadCharacteristic = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattReadCharacteristic',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattReadRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattReadResponse.FromString,
                _registered_method=True)
        self.GattWriteCharacteristic = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattWriteCharacteristic',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattWriteRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GattSubscribeCharacteristic = channel.unary_stream(
                '/api.gravity.v26.BluetoothService/GattSubscribeCharacteristic',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattSubscribeRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattNotification.FromString,
                _registered_method=True)
        self.GattReadDescriptor = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattReadDescriptor',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorReadResponse.FromString,
                _registered_method=True)
        self.GattWriteDescriptor = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattWriteDescriptor',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorWriteRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GattReadRssi = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/GattReadRssi',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattRssiResponse.FromString,
                _registered_method=True)
        self.RequestMtu = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/RequestMtu',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.MtuRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.MtuResponse.FromString,
                _registered_method=True)
        self.RequestConnectionPriority = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/RequestConnectionPriority',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.ConnectionPriorityRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.SetPreferredPhy = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/SetPreferredPhy',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.PhyRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.ReadPhy = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/ReadPhy',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
                response_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.PhyResponse.FromString,
                _registered_method=True)
        self.StartAdvertising = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/StartAdvertising',
                request_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.AdvertiseRequest.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.StopAdvertising = channel.unary_unary(
                '/api.gravity.v26.BluetoothService/StopAdvertising',
                request_serializer=api_dot_common_dot_types__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_common_dot_types__pb2.BooleanResponse.FromString,
                _registered_method=True)


class BluetoothServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    """

    def GetAdapterInfo(self, request, context):
        """Adapter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableBluetooth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableBluetooth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLocalName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDiscoverable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScan(self, request, context):
        """Classic Bluetooth — discovery
        Stream ends when the adapter finishes discovery or the client cancels the RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBondedDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BondDevice(self, request, context):
        """Classic Bluetooth — pairing
        BondDevice streams pairing events (state changes, PIN requests) until bonding completes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBond(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectDevice(self, request, context):
        """Classic Bluetooth — connection (profile-agnostic)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectionState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBleScan(self, request, context):
        """BLE — scan
        Stream delivers results continuously; cancel the RPC to stop scanning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattConnect(self, request, context):
        """BLE — GATT client: lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattDisconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGattState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattDiscoverServices(self, request, context):
        """BLE — GATT client: service & characteristic operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattReadCharacteristic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattWriteCharacteristic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattSubscribeCharacteristic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattReadDescriptor(self, request, context):
        """BLE — GATT client: descriptor operations (e.g. manual CCCD management)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattWriteDescriptor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GattReadRssi(self, request, context):
        """BLE — GATT client: link tuning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMtu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestConnectionPriority(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreferredPhy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPhy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAdvertising(self, request, context):
        """BLE — advertising (Pi acts as peripheral)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAdvertising(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BluetoothServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAdapterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdapterInfo,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BluetoothAdapterInfoResponse.SerializeToString,
            ),
            'EnableBluetooth': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableBluetooth,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisableBluetooth': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableBluetooth,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetLocalName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalName,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.StringResponse.SerializeToString,
            ),
            'SetLocalName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLocalName,
                    request_deserializer=api_dot_common_dot_types__pb2.StringRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'SetDiscoverable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDiscoverable,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.SetDiscoverableRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'StartScan': grpc.unary_stream_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.ClassicScanResult.SerializeToString,
            ),
            'GetBondedDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBondedDevices,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BondedDevicesResponse.SerializeToString,
            ),
            'BondDevice': grpc.unary_stream_rpc_method_handler(
                    servicer.BondDevice,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BondEvent.SerializeToString,
            ),
            'RemoveBond': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBond,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'ConnectDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectDevice,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'DisconnectDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectDevice,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetConnectionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectionState,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtConnectionStateResponse.SerializeToString,
            ),
            'StartBleScan': grpc.unary_stream_rpc_method_handler(
                    servicer.StartBleScan,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BleScanRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BleScanResult.SerializeToString,
            ),
            'GattConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.GattConnect,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GattDisconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.GattDisconnect,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GetGattState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGattState,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattStateResponse.SerializeToString,
            ),
            'GattDiscoverServices': grpc.unary_unary_rpc_method_handler(
                    servicer.GattDiscoverServices,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattServicesResponse.SerializeToString,
            ),
            'GattReadCharacteristic': grpc.unary_unary_rpc_method_handler(
                    servicer.GattReadCharacteristic,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattReadRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattReadResponse.SerializeToString,
            ),
            'GattWriteCharacteristic': grpc.unary_unary_rpc_method_handler(
                    servicer.GattWriteCharacteristic,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattWriteRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GattSubscribeCharacteristic': grpc.unary_stream_rpc_method_handler(
                    servicer.GattSubscribeCharacteristic,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattSubscribeRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattNotification.SerializeToString,
            ),
            'GattReadDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GattReadDescriptor,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorReadResponse.SerializeToString,
            ),
            'GattWriteDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GattWriteDescriptor,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorWriteRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'GattReadRssi': grpc.unary_unary_rpc_method_handler(
                    servicer.GattReadRssi,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattRssiResponse.SerializeToString,
            ),
            'RequestMtu': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMtu,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.MtuRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.MtuResponse.SerializeToString,
            ),
            'RequestConnectionPriority': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestConnectionPriority,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.ConnectionPriorityRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'SetPreferredPhy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreferredPhy,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.PhyRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'ReadPhy': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPhy,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.FromString,
                    response_serializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.PhyResponse.SerializeToString,
            ),
            'StartAdvertising': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAdvertising,
                    request_deserializer=api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.AdvertiseRequest.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
            'StopAdvertising': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAdvertising,
                    request_deserializer=api_dot_common_dot_types__pb2.Empty.FromString,
                    response_serializer=api_dot_common_dot_types__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.gravity.v26.BluetoothService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.gravity.v26.BluetoothService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BluetoothService(object):
    """─── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetAdapterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GetAdapterInfo',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BluetoothAdapterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableBluetooth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/EnableBluetooth',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableBluetooth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/DisableBluetooth',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocalName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GetLocalName',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.StringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLocalName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/SetLocalName',
            api_dot_common_dot_types__pb2.StringRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDiscoverable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/SetDiscoverable',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.SetDiscoverableRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.BluetoothService/StartScan',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.ClassicScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBondedDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GetBondedDevices',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BondedDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BondDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.BluetoothService/BondDevice',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BondEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/RemoveBond',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/ConnectDevice',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/DisconnectDevice',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GetConnectionState',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtConnectionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBleScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.BluetoothService/StartBleScan',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BleScanRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BleScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattConnect',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattDisconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattDisconnect',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGattState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GetGattState',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattDiscoverServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattDiscoverServices',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattReadCharacteristic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattReadCharacteristic',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattReadRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattWriteCharacteristic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattWriteCharacteristic',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattWriteRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattSubscribeCharacteristic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattSubscribeCharacteristic',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattSubscribeRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattReadDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattReadDescriptor',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattWriteDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattWriteDescriptor',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattDescriptorWriteRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GattReadRssi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/GattReadRssi',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.GattRssiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestMtu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/RequestMtu',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.MtuRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.MtuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestConnectionPriority(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/RequestConnectionPriority',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.ConnectionPriorityRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPreferredPhy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/SetPreferredPhy',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.PhyRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadPhy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/ReadPhy',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.BtDeviceRequest.SerializeToString,
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.PhyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAdvertising(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/StartAdvertising',
            api_dot_bluetooth__service_dot_v26_dot_bluetooth__service__pb2.AdvertiseRequest.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAdvertising(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.gravity.v26.BluetoothService/StopAdvertising',
            api_dot_common_dot_types__pb2.Empty.SerializeToString,
            api_dot_common_dot_types__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
