"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from api.bluetooth_service.v26 import bluetooth_service_pb2 as _bluetooth_service_pb2
from api.common import types_pb2 as _types_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class BluetoothServiceStub:
    """─── Service ──────────────────────────────────────────────────────────────────"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BluetoothServiceAsyncStub: ...
    GetAdapterInfo: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _bluetooth_service_pb2.BluetoothAdapterInfoResponse]
    """Adapter"""
    EnableBluetooth: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    DisableBluetooth: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]
    GetLocalName: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.StringResponse]
    SetLocalName: _grpc.UnaryUnaryMultiCallable[_types_pb2.StringRequest, _types_pb2.BooleanResponse]
    SetDiscoverable: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.SetDiscoverableRequest, _types_pb2.BooleanResponse]
    StartScan: _grpc.UnaryStreamMultiCallable[_types_pb2.Empty, _bluetooth_service_pb2.ClassicScanResult]
    """Classic Bluetooth — discovery
    Stream ends when the adapter finishes discovery or the client cancels the RPC
    """
    GetBondedDevices: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _bluetooth_service_pb2.BondedDevicesResponse]
    BondDevice: _grpc.UnaryStreamMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.BondEvent]
    """Classic Bluetooth — pairing
    BondDevice streams pairing events (state changes, PIN requests) until bonding completes
    """
    RemoveBond: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]
    ConnectDevice: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]
    """Classic Bluetooth — connection (profile-agnostic)"""
    DisconnectDevice: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]
    GetConnectionState: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.BtConnectionStateResponse]
    StartBleScan: _grpc.UnaryStreamMultiCallable[_bluetooth_service_pb2.BleScanRequest, _bluetooth_service_pb2.BleScanResult]
    """BLE — scan
    Stream delivers results continuously; cancel the RPC to stop scanning
    """
    GattConnect: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]
    """BLE — GATT client: lifecycle"""
    GattDisconnect: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]
    GetGattState: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.GattStateResponse]
    GattDiscoverServices: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.GattServicesResponse]
    """BLE — GATT client: service & characteristic operations"""
    GattReadCharacteristic: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattReadRequest, _bluetooth_service_pb2.GattReadResponse]
    GattWriteCharacteristic: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattWriteRequest, _types_pb2.BooleanResponse]
    GattSubscribeCharacteristic: _grpc.UnaryStreamMultiCallable[_bluetooth_service_pb2.GattSubscribeRequest, _bluetooth_service_pb2.GattNotification]
    GattReadDescriptor: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattDescriptorRequest, _bluetooth_service_pb2.GattDescriptorReadResponse]
    """BLE — GATT client: descriptor operations (e.g. manual CCCD management)"""
    GattWriteDescriptor: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattDescriptorWriteRequest, _types_pb2.BooleanResponse]
    GattReadRssi: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.GattRssiResponse]
    """BLE — GATT client: link tuning"""
    RequestMtu: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.MtuRequest, _bluetooth_service_pb2.MtuResponse]
    RequestConnectionPriority: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.ConnectionPriorityRequest, _types_pb2.BooleanResponse]
    SetPreferredPhy: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.PhyRequest, _types_pb2.BooleanResponse]
    ReadPhy: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.PhyResponse]
    StartAdvertising: _grpc.UnaryUnaryMultiCallable[_bluetooth_service_pb2.AdvertiseRequest, _types_pb2.BooleanResponse]
    """BLE — advertising (Pi acts as peripheral)"""
    StopAdvertising: _grpc.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]

@_typing.type_check_only
class BluetoothServiceAsyncStub(BluetoothServiceStub):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetAdapterInfo: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _bluetooth_service_pb2.BluetoothAdapterInfoResponse]  # type: ignore[assignment]
    """Adapter"""
    EnableBluetooth: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    DisableBluetooth: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetLocalName: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.StringResponse]  # type: ignore[assignment]
    SetLocalName: _aio.UnaryUnaryMultiCallable[_types_pb2.StringRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    SetDiscoverable: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.SetDiscoverableRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    StartScan: _aio.UnaryStreamMultiCallable[_types_pb2.Empty, _bluetooth_service_pb2.ClassicScanResult]  # type: ignore[assignment]
    """Classic Bluetooth — discovery
    Stream ends when the adapter finishes discovery or the client cancels the RPC
    """
    GetBondedDevices: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _bluetooth_service_pb2.BondedDevicesResponse]  # type: ignore[assignment]
    BondDevice: _aio.UnaryStreamMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.BondEvent]  # type: ignore[assignment]
    """Classic Bluetooth — pairing
    BondDevice streams pairing events (state changes, PIN requests) until bonding completes
    """
    RemoveBond: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    ConnectDevice: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """Classic Bluetooth — connection (profile-agnostic)"""
    DisconnectDevice: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetConnectionState: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.BtConnectionStateResponse]  # type: ignore[assignment]
    StartBleScan: _aio.UnaryStreamMultiCallable[_bluetooth_service_pb2.BleScanRequest, _bluetooth_service_pb2.BleScanResult]  # type: ignore[assignment]
    """BLE — scan
    Stream delivers results continuously; cancel the RPC to stop scanning
    """
    GattConnect: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """BLE — GATT client: lifecycle"""
    GattDisconnect: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GetGattState: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.GattStateResponse]  # type: ignore[assignment]
    GattDiscoverServices: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.GattServicesResponse]  # type: ignore[assignment]
    """BLE — GATT client: service & characteristic operations"""
    GattReadCharacteristic: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattReadRequest, _bluetooth_service_pb2.GattReadResponse]  # type: ignore[assignment]
    GattWriteCharacteristic: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattWriteRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GattSubscribeCharacteristic: _aio.UnaryStreamMultiCallable[_bluetooth_service_pb2.GattSubscribeRequest, _bluetooth_service_pb2.GattNotification]  # type: ignore[assignment]
    GattReadDescriptor: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattDescriptorRequest, _bluetooth_service_pb2.GattDescriptorReadResponse]  # type: ignore[assignment]
    """BLE — GATT client: descriptor operations (e.g. manual CCCD management)"""
    GattWriteDescriptor: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.GattDescriptorWriteRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    GattReadRssi: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.GattRssiResponse]  # type: ignore[assignment]
    """BLE — GATT client: link tuning"""
    RequestMtu: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.MtuRequest, _bluetooth_service_pb2.MtuResponse]  # type: ignore[assignment]
    RequestConnectionPriority: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.ConnectionPriorityRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    SetPreferredPhy: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.PhyRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    ReadPhy: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.BtDeviceRequest, _bluetooth_service_pb2.PhyResponse]  # type: ignore[assignment]
    StartAdvertising: _aio.UnaryUnaryMultiCallable[_bluetooth_service_pb2.AdvertiseRequest, _types_pb2.BooleanResponse]  # type: ignore[assignment]
    """BLE — advertising (Pi acts as peripheral)"""
    StopAdvertising: _aio.UnaryUnaryMultiCallable[_types_pb2.Empty, _types_pb2.BooleanResponse]  # type: ignore[assignment]

class BluetoothServiceServicer(metaclass=_abc_1.ABCMeta):
    """─── Service ──────────────────────────────────────────────────────────────────"""

    @_abc_1.abstractmethod
    def GetAdapterInfo(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.BluetoothAdapterInfoResponse, _abc.Awaitable[_bluetooth_service_pb2.BluetoothAdapterInfoResponse]]:
        """Adapter"""

    @_abc_1.abstractmethod
    def EnableBluetooth(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def DisableBluetooth(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetLocalName(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.StringResponse, _abc.Awaitable[_types_pb2.StringResponse]]: ...

    @_abc_1.abstractmethod
    def SetLocalName(
        self,
        request: _types_pb2.StringRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def SetDiscoverable(
        self,
        request: _bluetooth_service_pb2.SetDiscoverableRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def StartScan(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_bluetooth_service_pb2.ClassicScanResult], _abc.AsyncIterator[_bluetooth_service_pb2.ClassicScanResult]]:
        """Classic Bluetooth — discovery
        Stream ends when the adapter finishes discovery or the client cancels the RPC
        """

    @_abc_1.abstractmethod
    def GetBondedDevices(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.BondedDevicesResponse, _abc.Awaitable[_bluetooth_service_pb2.BondedDevicesResponse]]: ...

    @_abc_1.abstractmethod
    def BondDevice(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_bluetooth_service_pb2.BondEvent], _abc.AsyncIterator[_bluetooth_service_pb2.BondEvent]]:
        """Classic Bluetooth — pairing
        BondDevice streams pairing events (state changes, PIN requests) until bonding completes
        """

    @_abc_1.abstractmethod
    def RemoveBond(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def ConnectDevice(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """Classic Bluetooth — connection (profile-agnostic)"""

    @_abc_1.abstractmethod
    def DisconnectDevice(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetConnectionState(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.BtConnectionStateResponse, _abc.Awaitable[_bluetooth_service_pb2.BtConnectionStateResponse]]: ...

    @_abc_1.abstractmethod
    def StartBleScan(
        self,
        request: _bluetooth_service_pb2.BleScanRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_bluetooth_service_pb2.BleScanResult], _abc.AsyncIterator[_bluetooth_service_pb2.BleScanResult]]:
        """BLE — scan
        Stream delivers results continuously; cancel the RPC to stop scanning
        """

    @_abc_1.abstractmethod
    def GattConnect(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """BLE — GATT client: lifecycle"""

    @_abc_1.abstractmethod
    def GattDisconnect(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GetGattState(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.GattStateResponse, _abc.Awaitable[_bluetooth_service_pb2.GattStateResponse]]: ...

    @_abc_1.abstractmethod
    def GattDiscoverServices(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.GattServicesResponse, _abc.Awaitable[_bluetooth_service_pb2.GattServicesResponse]]:
        """BLE — GATT client: service & characteristic operations"""

    @_abc_1.abstractmethod
    def GattReadCharacteristic(
        self,
        request: _bluetooth_service_pb2.GattReadRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.GattReadResponse, _abc.Awaitable[_bluetooth_service_pb2.GattReadResponse]]: ...

    @_abc_1.abstractmethod
    def GattWriteCharacteristic(
        self,
        request: _bluetooth_service_pb2.GattWriteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GattSubscribeCharacteristic(
        self,
        request: _bluetooth_service_pb2.GattSubscribeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_bluetooth_service_pb2.GattNotification], _abc.AsyncIterator[_bluetooth_service_pb2.GattNotification]]: ...

    @_abc_1.abstractmethod
    def GattReadDescriptor(
        self,
        request: _bluetooth_service_pb2.GattDescriptorRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.GattDescriptorReadResponse, _abc.Awaitable[_bluetooth_service_pb2.GattDescriptorReadResponse]]:
        """BLE — GATT client: descriptor operations (e.g. manual CCCD management)"""

    @_abc_1.abstractmethod
    def GattWriteDescriptor(
        self,
        request: _bluetooth_service_pb2.GattDescriptorWriteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def GattReadRssi(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.GattRssiResponse, _abc.Awaitable[_bluetooth_service_pb2.GattRssiResponse]]:
        """BLE — GATT client: link tuning"""

    @_abc_1.abstractmethod
    def RequestMtu(
        self,
        request: _bluetooth_service_pb2.MtuRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.MtuResponse, _abc.Awaitable[_bluetooth_service_pb2.MtuResponse]]: ...

    @_abc_1.abstractmethod
    def RequestConnectionPriority(
        self,
        request: _bluetooth_service_pb2.ConnectionPriorityRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def SetPreferredPhy(
        self,
        request: _bluetooth_service_pb2.PhyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

    @_abc_1.abstractmethod
    def ReadPhy(
        self,
        request: _bluetooth_service_pb2.BtDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_bluetooth_service_pb2.PhyResponse, _abc.Awaitable[_bluetooth_service_pb2.PhyResponse]]: ...

    @_abc_1.abstractmethod
    def StartAdvertising(
        self,
        request: _bluetooth_service_pb2.AdvertiseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]:
        """BLE — advertising (Pi acts as peripheral)"""

    @_abc_1.abstractmethod
    def StopAdvertising(
        self,
        request: _types_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.BooleanResponse, _abc.Awaitable[_types_pb2.BooleanResponse]]: ...

def add_BluetoothServiceServicer_to_server(servicer: BluetoothServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
